### ISSUE TITLE
I didn't see the sd-cn-animation extension on the tab

### ISSUE THREAD

**Issue by modernbaby** [volotat/SD-CN-Animation#105]
I installed "sd-cn-animation" on the SD WebUI, but after restarting the UI, I didn't see the sd-cn-animation extension on the tab. I confirmed that the extension was installed correctly. My runtime environment is Colab, and every time I run it, I get the following prompt: "Installing SD-CN-Animation requirement: scikit-image==0.19.2." 

Does anyone know what I did wrong?

**Comment by PandorasParabox** [comment]
im having this same issue in auto1111

**Comment by PandorasParabox** [comment]
i updated auto1111, problem solved! :)

**Comment by modernbaby** [comment]
> i updated auto1111, problem solved! :)

Hi, How to updat it in colab?

**Comment by modernbaby** [comment]
I found error message: Error executing callback ui_tabs_callback for /content/drive/MyDrive/stable-diffusion-webui-colab/stable-diffusion-webui/extensions/SD-CN-Animation/scripts/base_ui.py
Traceback (most recent call last):
  File "/content/drive/MyDrive/stable-diffusion-webui-colab/stable-diffusion-webui/modules/script_callbacks.py", line 125, in ui_tabs_callback
    res += c.callback() or []
  File "/content/drive/MyDrive/stable-diffusion-webui-colab/stable-diffusion-webui/extensions/SD-CN-Animation/scripts/base_ui.py", line 210, in on_ui_tabs
    export_setting_json = gr.Code(value='')
AttributeError: module 'gradio' has no attribute 'Code'

anyone help me?

**Comment by Apatiste** [comment]
Same issue here

**Comment by fafayqa** [comment]
I am on SD 1.10.1, I installed SD-CN-Animation but the tab doe snot show up at all.
