### ISSUE TITLE
I found error message: Error executing callback ui_tabs_callback for /content/drive/MyDrive/stable-diffusion-webui-colab/stable-diffusion-webui/extensions/SD-CN-Animation/scripts/base_ui.py

### ISSUE THREAD

**Issue by modernbaby** [volotat/SD-CN-Animation#114]
I found error message: Error executing callback ui_tabs_callback for /content/drive/MyDrive/stable-diffusion-webui-colab/stable-diffusion-webui/extensions/SD-CN-Animation/scripts/base_ui.py
Traceback (most recent call last):
  File "/content/drive/MyDrive/stable-diffusion-webui-colab/stable-diffusion-webui/modules/script_callbacks.py", line 125, in ui_tabs_callback
    res += c.callback() or []
  File "/content/drive/MyDrive/stable-diffusion-webui-colab/stable-diffusion-webui/extensions/SD-CN-Animation/scripts/base_ui.py", line 210, in on_ui_tabs
    export_setting_json = gr.Code(value='')
AttributeError: module 'gradio' has no attribute 'Code'

anyone help me?

_Originally posted by @modernbaby in https://github.com/volotat/SD-CN-Animation/issues/105#issuecomment-1550877554_

**Comment by rover1003** [comment]
me too

**Comment by volotat** [comment]
Check out this disscussion. https://github.com/volotat/SD-CN-Animation/discussions/106 Simple webui update seems to fix it.
