### ISSUE TITLE
An exception occurred while trying to process the frame: invalid load key, '<'.

### ISSUE THREAD

**Issue by oivio** [volotat/SD-CN-Animation#117]
while processing vid2vid I am getting error:

`An exception occurred while trying to process the frame: invalid load key, '<'.
Traceback (most recent call last):
  File "J:/AI/seait_installers_version_0.1.4/automatic/extensions/SD-CN-Animation\scripts\base_ui.py", line 139, in process
    yield from vid2vid.start_process(*args)
  File "J:\AI/seait_installers_version_0.1.4/automatic/extensions/SD-CN-Animation\scripts\core\vid2vid.py", line 149, in start_process
    next_flow, prev_flow, occlusion_mask = RAFT_estimate_flow(prev_frame, curr_frame, device=device)
  File "J:\AI/seait_installers_version_0.1.4/automatic/extensions/SD-CN-Animation\scripts\core\flow_utils.py", line 55, in RAFT_estimate_flow
    RAFT_model.load_state_dict(torch.load(args.model))
  File "J:\AI\seait_installers_version_0.1.4\automatic\venv\lib\site-packages\torch\serialization.py", line 815, in load    return _legacy_load(opened_file, map_location, pickle_module, **pickle_load_args)
  File "J:\AI\seait_installers_version_0.1.4\automatic\venv\lib\site-packages\torch\serialization.py", line 1033, in _legacy_load
    magic_number = pickle_module.load(f, **pickle_load_args)
_pickle.UnpicklingError: invalid load key, '<'.`

I did not change any settings, just changed mode to revanimated and press it to genrate. Vid is 1.2mb and 480x854 mp4

**Comment by thpschris** [comment]
I also have this issue - seems to happen regardless of the model selected, about 1-15 frames in. Txt to video works fine, but it's not exactly the same thing.

**Comment by Death-777** [comment]
I too am having this issue and nothing I've been able to change seems to do anything to fix the problem, no clue.
