### ISSUE TITLE
unable to open flow.h5

### ISSUE THREAD

**Issue by theseraphim** [volotat/SD-CN-Animation#12]
(raft) I:\stable-diffusion-webui>python vid2vid.py
Traceback (most recent call last):
  File "vid2vid.py", line 145, in <module>
    with h5py.File(FLOW_MAPS, 'r') as f:
  File "C:\Users\david\miniconda3\envs\raft\lib\site-packages\h5py\_hl\files.py", line 567, in __init__
    fid = make_fid(name, mode, userblock_size, fapl, fcpl, swmr=swmr)
  File "C:\Users\david\miniconda3\envs\raft\lib\site-packages\h5py\_hl\files.py", line 231, in make_fid
    fid = h5f.open(name, flags, fapl=fapl)
  File "h5py\_objects.pyx", line 54, in h5py._objects.with_phil.wrapper
  File "h5py\_objects.pyx", line 55, in h5py._objects.with_phil.wrapper
  File "h5py\h5f.pyx", line 106, in h5py.h5f.open
FileNotFoundError: [Errno 2] Unable to open file (unable to open file: name = 'i:/flow.h5', errno = 2, error message = 'No such file or directory', flags = 0, o_flags = 0)

**Comment by theseraphim** [comment]
yeah, or i could read all of the instructions and run the compute_flow.py first. smh
