### ISSUE TITLE
 could not convert string to float: ' '

### ISSUE THREAD

**Issue by djay29** [volotat/SD-CN-Animation#122]
Traceback (most recent call last):
  File "E:\stable-diffusion-webui-directml\venv\lib\site-packages\gradio\routes.py", line 408, in run_predict
    output = await app.get_blocks().process_api(
  File "E:\stable-diffusion-webui-directml\venv\lib\site-packages\gradio\blocks.py", line 1313, in process_api
    inputs = self.preprocess_data(fn_index, inputs, state)
  File "E:\stable-diffusion-webui-directml\venv\lib\site-packages\gradio\blocks.py", line 1163, in preprocess_data
    processed_input.append(block.preprocess(inputs[i]))
  File "E:\stable-diffusion-webui-directml\venv\lib\site-packages\gradio\components.py", line 704, in preprocess
    return self._round_to_precision(x, self.precision)
  File "E:\stable-diffusion-webui-directml\venv\lib\site-packages\gradio\components.py", line 666, in _round_to_precision
    return float(num)
ValueError: could not convert string to float: ''

**Comment by djay29** [comment]
While txt2video it is giving this error.
