### ISSUE TITLE
An exception occurred while trying to process the frame: tensor.device().type() == at::DeviceType::PrivateUse1 INTERNAL ASSERT FAILED at "D:\\a\\_work\\1\\s\\pytorch-directml-plugin\\torch_directml\\csrc\\dml\\DMLTensor.cpp":31, please report a bug to PyTorch. unbox expects Dml at::Tensor as inputs

### ISSUE THREAD

**Issue by djay29** [volotat/SD-CN-Animation#124]
An exception occurred while trying to process the frame: tensor.device().type() == at::DeviceType::PrivateUse1 INTERNAL ASSERT FAILED at "D:\\a\\_work\\1\\s\\pytorch-directml-plugin\\torch_directml\\csrc\\dml\\DMLTensor.cpp":31, please report a bug to PyTorch. unbox expects Dml at::Tensor as inputs
Traceback (most recent call last):
  File "E:\stable-diffusion-webui-directml\extensions\SD-CN-Animation\scripts\base_ui.py", line 139, in process
    yield from vid2vid.start_process(*args)
  File "E:\stable-diffusion-webui-directml\extensions\SD-CN-Animation\scripts\core\vid2vid.py", line 149, in start_process
    next_flow, prev_flow, occlusion_mask = RAFT_estimate_flow(prev_frame, curr_frame, device=device)
  File "E:\stable-diffusion-webui-directml\extensions\SD-CN-Animation\scripts\core\flow_utils.py", line 69, in RAFT_estimate_flow
    _, next_flow = RAFT_model(image1, image2, iters=20, test_mode=True)
  File "E:\stable-diffusion-webui-directml\venv\lib\site-packages\torch\nn\modules\module.py", line 1501, in _call_impl
    return forward_call(*args, **kwargs)
  File "E:\stable-diffusion-webui-directml\venv\lib\site-packages\torch\nn\parallel\data_parallel.py", line 153, in forward
    return self.module(*inputs, **kwargs)
  File "E:\stable-diffusion-webui-directml\venv\lib\site-packages\torch\nn\modules\module.py", line 1501, in _call_impl
    return forward_call(*args, **kwargs)
  File "E:\stable-diffusion-webui-directml\extensions\SD-CN-Animation\RAFT\raft.py", line 100, in forward
    fmap1, fmap2 = self.fnet([image1, image2])
  File "E:\stable-diffusion-webui-directml\venv\lib\site-packages\torch\nn\modules\module.py", line 1501, in _call_impl
    return forward_call(*args, **kwargs)
  File "E:\stable-diffusion-webui-directml\extensions\SD-CN-Animation\RAFT\extractor.py", line 176, in forward
    x = self.conv1(x)
  File "E:\stable-diffusion-webui-directml\venv\lib\site-packages\torch\nn\modules\module.py", line 1501, in _call_impl
    return forward_call(*args, **kwargs)
  File "E:\stable-diffusion-webui-directml\extensions-builtin\Lora\lora.py", line 376, in lora_Conv2d_forward
    return torch.nn.Conv2d_forward_before_lora(self, input)
  File "E:\stable-diffusion-webui-directml\venv\lib\site-packages\torch\nn\modules\conv.py", line 463, in forward
    return self._conv_forward(input, self.weight, self.bias)
  File "E:\stable-diffusion-webui-directml\venv\lib\site-packages\torch\nn\modules\conv.py", line 459, in _conv_forward
    return F.conv2d(input, weight, bias, self.stride,
  File "E:\stable-diffusion-webui-directml\modules\dml\amp\autocast_mode.py", line 32, in <lambda>
    setattr(resolved_obj, func_path[-1], lambda *args, **kwargs: pre_forward(op, args, kwargs))
  File "E:\stable-diffusion-webui-directml\modules\dml\amp\autocast_mode.py", line 9, in pre_forward
    return forward(*args, **kwargs)
RuntimeError: tensor.device().type() == at::DeviceType::PrivateUse1 INTERNAL ASSERT FAILED at "D:\\a\\_work\\1\\s\\pytorch-directml-plugin\\torch_directml\\csrc\\dml\\DMLTensor.cpp":31, please report a bug to PyTorch. unbox expects Dml at::Tensor as inputs

**Comment by system3600** [comment]
@djay29 did you manage to get txt2vid or vid2vid to work on an AMD card? How did you do that?

**Comment by djay29** [comment]
It is not working on AMD gpus. It was able generate only one frame in txt2vid after that there is another error which is also reported by me
