### ISSUE TITLE
CN Model button non functional (Apple M1 Ultra)

### ISSUE THREAD

**Issue by mynameisbill** [volotat/SD-CN-Animation#142]
The Model selection button in Control Net is non-functional within SD-CN. This is possibly the same problem that has been discussed in [this issue](https://github.com/volotat/SD-CN-Animation/issues/109). The only solve that I can see is just turning off SD-CN. That's great... but I would actually love to use SD-CN. 

https://github.com/volotat/SD-CN-Animation/assets/6685618/c11a84de-1e75-4b4c-ae6d-229dbe4ecf4c

Here's the code when run without a model: 

100%|███████████████████████████████████████████| 13/13 [00:03<00:00,  3.45it/s]
Total progress: 100%|███████████████████████████| 13/13 [00:03<00:00,  3.53it/s]
Error running process: /Users/bill.bowles/stable-diffusion-webui/extensions/sd-webui-controlnet/scripts/controlnet.py
Traceback (most recent call last):
  File "/Users/bill.bowles/stable-diffusion-webui/modules/scripts.py", line 418, in process
    script.process(p, *script_args)
  File "/Users/bill.bowles/stable-diffusion-webui/extensions/sd-webui-controlnet/scripts/controlnet.py", line 1075, in process
    model_net = self.load_control_model(p, unet, unit.model, unit.low_vram)
  File "/Users/bill.bowles/stable-diffusion-webui/extensions/sd-webui-controlnet/scripts/controlnet.py", line 735, in load_control_model
    model_net = self.build_control_model(p, unet, model, lowvram)
  File "/Users/bill.bowles/stable-diffusion-webui/extensions/sd-webui-controlnet/scripts/controlnet.py", line 744, in build_control_model
    raise RuntimeError(f"You have not selected any ControlNet Model.")
RuntimeError: You have not selected any ControlNet Model.

I'm really hoping that I'm just a total bonehead, and that someone will tell me that I'm using the button wrong. Anyone else having this issue? Thanks!

**Comment by mynameisbill** [comment]
I AM a total bonehead. I had no models installed.
