### ISSUE TITLE
Attempting to deserialize object on a CUDA device but torch.cuda.is_available() is False. If you are running on a CPU-only machine, please use torch.load with map_location=torch.device('cpu') to map your storages to the CPU.

### ISSUE THREAD

**Issue by melbouhy** [volotat/SD-CN-Animation#145]
Hello, 
I am trying to use SD-CN on **Macbook M2 device** and in the end of the generation of **vid2vid** I have the following error
'An exception occurred while trying to process the frame: Attempting to deserialize object on a CUDA device but torch.cuda.is_available() is False. If you are running on a CPU-only machine, please use torch.load with map_location=torch.device('cpu') to map your storages to the CPU.
Traceback (most recent call last):
  File "/stable-diffusion-webui/extensions/SD-CN-Animation/scripts/base_ui.py", line 144, in process
    yield from vid2vid.start_process(*args)
  File "/stable-diffusion-webui/extensions/SD-CN-Animation/scripts/core/vid2vid.py", line 152, in start_process
    next_flow, prev_flow, occlusion_mask = RAFT_estimate_flow(prev_frame, curr_frame, device=device)
  File "/stable-diffusion-webui/extensions/SD-CN-Animation/scripts/core/flow_utils.py", line 55, in RAFT_estimate_flow
    RAFT_model.load_state_dict(torch.load(args.model))
  File "/stable-diffusion-webui/modules/safe.py", line 107, in load
    return load_with_extra(filename, *args, extra_handler=global_extra_handler, **kwargs)
  File "/stable-diffusion-webui/modules/safe.py", line 152, in load_with_extra
    return unsafe_torch_load(filename, *args, **kwargs)
  File "/stable-diffusion-webui/venv/lib/python3.10/site-packages/torch/serialization.py", line 712, in load
    return _load(opened_zipfile, map_location, pickle_module, **pickle_load_args)
  File "/stable-diffusion-webui/venv/lib/python3.10/site-packages/torch/serialization.py", line 1049, in _load
    result = unpickler.load()
  File "/Users/melbouhy/anaconda3/lib/python3.10/pickle.py", line 1213, in load
    dispatch[key[0]](self)
  File "/Users/melbouhy/anaconda3/lib/python3.10/pickle.py", line 1254, in load_binpersid
    self.append(self.persistent_load(pid))
  File "/stable-diffusion-webui/venv/lib/python3.10/site-packages/torch/serialization.py", line 1019, in persistent_load
    load_tensor(dtype, nbytes, key, _maybe_decode_ascii(location))
  File "/stable-diffusion-webui/venv/lib/python3.10/site-packages/torch/serialization.py", line 1001, in load_tensor
    wrap_storage=restore_location(storage, location),
  File "/stable-diffusion-webui/venv/lib/python3.10/site-packages/torch/serialization.py", line 175, in default_restore_location
    result = fn(storage, location)
  File "/stable-diffusion-webui/venv/lib/python3.10/site-packages/torch/serialization.py", line 152, in _cuda_deserialize
    device = validate_cuda_device(location)
  File "/stable-diffusion-webui/venv/lib/python3.10/site-packages/torch/serialization.py", line 136, in validate_cuda_device
    raise RuntimeError('Attempting to deserialize object on a CUDA '
RuntimeError: Attempting to deserialize object on a CUDA device but torch.cuda.is_available() is False. If you are running on a CPU-only machine, please use torch.load with map_location=torch.device('cpu') to map your storages to the CPU.'

I tried to add 
`device = torch.device("cpu")` after 
`if sdcn_anim_tmp.process_counter % prepare_steps == 0 and not sdcn_anim_tmp.frames_prepared: # prepare next 10 frames for processing`
but it doesn't help

Could you please help me out? 
Thanks

**Comment by system3600** [comment]
same error

**Comment by vapidvim** [comment]
Getting similar error. Was working fine before todays update. 

"An exception occurred while trying to process the frame: Torch not compiled with CUDA enabled"

**Comment by system3600** [comment]
An exception occurred while trying to process the frame: tensor.device().type() == at::DeviceType::PrivateUse1 INTERNAL ASSERT FAILED at "D:\\a\\_work\\1\\s\\pytorch-directml-plugin\\torch_directml\\csrc\\dml\\DMLTensor.cpp":31, please report a bug to PyTorch. unbox expects Dml at::Tensor as inputs
Traceback (most recent call last):
  File "C:\Users\Administrator\Desktop\SD\stable-diffusion-webui-directml\extensions\SD-CN-Animation\scripts\base_ui.py", line 140, in process
    yield from vid2vid.start_process(*args)
  File "C:\Users\Administrator\Desktop\SD\stable-diffusion-webui-directml\extensions\SD-CN-Animation\scripts\core\vid2vid.py", line 149, in start_process
    next_flow, prev_flow, occlusion_mask = RAFT_estimate_flow(prev_frame, curr_frame, device=device)
  File "C:\Users\Administrator\Desktop\SD\stable-diffusion-webui-directml\extensions\SD-CN-Animation\scripts\core\flow_utils.py", line 69, in RAFT_estimate_flow
    _, next_flow = RAFT_model(image1, image2, iters=20, test_mode=True)
  File "C:\Users\Administrator\Desktop\SD\stable-diffusion-webui-directml\venv\lib\site-packages\torch\nn\modules\module.py", line 1501, in _call_impl
    return forward_call(*args, **kwargs)
  File "C:\Users\Administrator\Desktop\SD\stable-diffusion-webui-directml\venv\lib\site-packages\torch\nn\parallel\data_parallel.py", line 153, in forward
    return self.module(*inputs, **kwargs)
  File "C:\Users\Administrator\Desktop\SD\stable-diffusion-webui-directml\venv\lib\site-packages\torch\nn\modules\module.py", line 1501, in _call_impl
    return forward_call(*args, **kwargs)
  File "C:\Users\Administrator\Desktop\SD\stable-diffusion-webui-directml\extensions\SD-CN-Animation\RAFT\raft.py", line 100, in forward
    fmap1, fmap2 = self.fnet([image1, image2])
  File "C:\Users\Administrator\Desktop\SD\stable-diffusion-webui-directml\venv\lib\site-packages\torch\nn\modules\module.py", line 1501, in _call_impl
    return forward_call(*args, **kwargs)
  File "C:\Users\Administrator\Desktop\SD\stable-diffusion-webui-directml\extensions\SD-CN-Animation\RAFT\extractor.py", line 176, in forward
    x = self.conv1(x)
  File "C:\Users\Administrator\Desktop\SD\stable-diffusion-webui-directml\venv\lib\site-packages\torch\nn\modules\module.py", line 1501, in _call_impl
    return forward_call(*args, **kwargs)
  File "C:\Users\Administrator\Desktop\SD\stable-diffusion-webui-directml\extensions-builtin\Lora\lora.py", line 415, in lora_Conv2d_forward
    return torch.nn.Conv2d_forward_before_lora(self, input)
  File "C:\Users\Administrator\Desktop\SD\stable-diffusion-webui-directml\venv\lib\site-packages\torch\nn\modules\conv.py", line 463, in forward
    return self._conv_forward(input, self.weight, self.bias)
  File "C:\Users\Administrator\Desktop\SD\stable-diffusion-webui-directml\venv\lib\site-packages\torch\nn\modules\conv.py", line 459, in _conv_forward
    return F.conv2d(input, weight, bias, self.stride,
  File "C:\Users\Administrator\Desktop\SD\stable-diffusion-webui-directml\modules\dml\amp\autocast_mode.py", line 32, in <lambda>
    setattr(resolved_obj, func_path[-1], lambda *args, **kwargs: pre_forward(op, args, kwargs))
  File "C:\Users\Administrator\Desktop\SD\stable-diffusion-webui-directml\modules\dml\amp\autocast_mode.py", line 9, in pre_forward
    return forward(*args, **kwargs)
RuntimeError: tensor.device().type() == at::DeviceType::PrivateUse1 INTERNAL ASSERT FAILED at "D:\\a\\_work\\1\\s\\pytorch-directml-plugin\\torch_directml\\csrc\\dml\\DMLTensor.cpp":31, please report a bug to PyTorch. unbox expects Dml at::Tensor as inputs


probably an error of the modified version I'm using, some way to fix it?

**Comment by system3600** [comment]
@vapidvim  looks like it's not working, the error continues after 1 frame generation

**Comment by vapidvim** [comment]
@system3600 delete the folder and replace with the build from 5 days ago I linked above. It should work after you restart your terminal session.

**Comment by system3600** [comment]
@vapidvim 

I'll leave the console log, maybe it will help

venv "C:\Users\Administrator\Desktop\SD\stable-diffusion-webui-directml\venv\Scripts\Python.exe"
fatal: No names found, cannot describe anything.
Python 3.10.6 (tags/v3.10.6:9c7b4bd, Aug  1 2022, 21:53:49) [MSC v.1932 64 bit (AMD64)]
Version: <none>
Commit hash: 8f1287355426216eb24332a64f9b4bf44256c699
Installing requirements



Installing requirements 1 for Infinite-Zoom

Installing requirements for Prompt Gallery

Installing SD-CN-Animation requirement: changing scikit-image version from 0.20.0 to 0.19.2

No module 'xformers'. Proceeding without it.
Warning: caught exception 'Torch not compiled with CUDA enabled', memory monitor disabled


Installing opencv-python
Installing opencv-python for pixel extension


Installing sd-webui-infinite-image-browsing requirement: python-dotenv
Installing sd-webui-infinite-image-browsing requirement: Pillow





Launching Web UI with arguments: --medvram --precision autocast --ckpt-dir E:\Ia ckpt --disable-safe-unpickle --opt-split-attention-v1 --lora-dir D:\IA - Lora
No module 'xformers'. Proceeding without it.
Warning: caught exception 'Torch not compiled with CUDA enabled', memory monitor disabled
[-] ADetailer initialized. version: 23.6.0, num models: 8
Loading booru2prompt settings
2023-06-01 15:21:15,468 - sd_dynamic_prompts.dynamic_prompting - INFO - Starting Dynamic Prompts v2.11.10
ControlNet v1.1.204
ControlNet v1.1.204
Image Browser: ImageReward is not installed, cannot be used.
[text2prompt] Following databases are available:
    all-mpnet-base-v2 : danbooru_strict
Loading weights [6ce0161689] from C:\Users\Administrator\Desktop\SD\stable-diffusion-webui-directml\models\Stable-diffusion\v1-5-pruned-emaonly.safetensors
Create LRU cache (max_size=16) for preprocessor results.
Creating model from config: C:\Users\Administrator\Desktop\SD\stable-diffusion-webui-directml\configs\v1-inference.yaml
LatentDiffusion: Running in eps-prediction mode
DiffusionWrapper has 859.52 M params.
Create LRU cache (max_size=16) for preprocessor results.
INFO:     Started server process [4548]
INFO:     Waiting for application startup.
INFO:     Application startup complete.
INFO:     Uvicorn running on http://127.0.0.1:5173 (Press CTRL+C to quit)
INFO:     127.0.0.1:52171 - "GET / HTTP/1.1" 200 OK
Create LRU cache (max_size=16) for preprocessor results.
add tab
Loading VAE weights specified in settings: C:\Users\Administrator\Desktop\SD\stable-diffusion-webui-directml\models\VAE\anything-v4.0.vae.pt
Applying optimization: V1... done.
Textual inversion embeddings loaded(0):
Model loaded in 21.3s (load weights from disk: 0.5s, create model: 0.5s, apply weights to model: 15.4s, apply half(): 3.5s, load VAE: 1.3s).
[text2prompt] Loading database with name "all-mpnet-base-v2 : danbooru_strict"...
[text2prompt] Database loaded
Running on local URL:  http://127.0.0.1:7860

To create a public link, set `share=True` in `launch()`.
Create LRU cache (max_size=16) for preprocessor results.
Startup time: 48.2s (import torch: 1.5s, import gradio: 1.1s, import ldm: 0.6s, other imports: 0.8s, setup codeformer: 0.1s, list SD models: 0.2s, load scripts: 13.7s, create ui: 29.0s, gradio launch: 1.1s).
2023-06-01 15:23:41,712 - sd_dynamic_prompts.dynamic_prompting - INFO - Prompt matrix will create 1 images in a total of 1 batches.
100%|██████████████████████████████████████████████████████████████████████████████████| 12/12 [00:34<00:00,  2.85s/it]
Total progress: 100%|██████████████████████████████████████████████████████████████████| 12/12 [00:33<00:00,  2.78s/it]
An exception occurred while trying to process the frame: Attempting to deserialize object on a CUDA device but torch.cuda.is_available() is False. If you are running on a CPU-only machine, please use torch.load with map_location=torch.device('cpu') to map your storages to the CPU.
Traceback (most recent call last):
  File "C:\Users\Administrator\Desktop\SD\stable-diffusion-webui-directml\extensions\SD-CN-Animation-c3c0972c0a3a2697533f662ab2e9cb24413fbd0c\scripts\base_ui.py", line 140, in process
    yield from vid2vid.start_process(*args)
  File "C:\Users\Administrator\Desktop\SD\stable-diffusion-webui-directml\extensions\SD-CN-Animation-c3c0972c0a3a2697533f662ab2e9cb24413fbd0c\scripts\core\vid2vid.py", line 149, in start_process
    next_flow, prev_flow, occlusion_mask = RAFT_estimate_flow(prev_frame, curr_frame, device=device)
  File "C:\Users\Administrator\Desktop\SD\stable-diffusion-webui-directml\extensions\SD-CN-Animation-c3c0972c0a3a2697533f662ab2e9cb24413fbd0c\scripts\core\flow_utils.py", line 55, in RAFT_estimate_flow
    RAFT_model.load_state_dict(torch.load(args.model))
  File "C:\Users\Administrator\Desktop\SD\stable-diffusion-webui-directml\modules\safe.py", line 107, in load
    return load_with_extra(filename, *args, extra_handler=global_extra_handler, **kwargs)
  File "C:\Users\Administrator\Desktop\SD\stable-diffusion-webui-directml\modules\safe.py", line 152, in load_with_extra    return unsafe_torch_load(filename, *args, **kwargs)
  File "C:\Users\Administrator\Desktop\SD\stable-diffusion-webui-directml\venv\lib\site-packages\torch\serialization.py", line 809, in load
    return _load(opened_zipfile, map_location, pickle_module, **pickle_load_args)
  File "C:\Users\Administrator\Desktop\SD\stable-diffusion-webui-directml\venv\lib\site-packages\torch\serialization.py", line 1172, in _load
    result = unpickler.load()
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python310\lib\pickle.py", line 1213, in load
    dispatch[key[0]](self)
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python310\lib\pickle.py", line 1254, in load_binpersid
    self.append(self.persistent_load(pid))
  File "C:\Users\Administrator\Desktop\SD\stable-diffusion-webui-directml\venv\lib\site-packages\torch\serialization.py", line 1142, in persistent_load
    typed_storage = load_tensor(dtype, nbytes, key, _maybe_decode_ascii(location))
  File "C:\Users\Administrator\Desktop\SD\stable-diffusion-webui-directml\venv\lib\site-packages\torch\serialization.py", line 1116, in load_tensor
    wrap_storage=restore_location(storage, location),
  File "C:\Users\Administrator\Desktop\SD\stable-diffusion-webui-directml\venv\lib\site-packages\torch\serialization.py", line 217, in default_restore_location
    result = fn(storage, location)
  File "C:\Users\Administrator\Desktop\SD\stable-diffusion-webui-directml\venv\lib\site-packages\torch\serialization.py", line 182, in _cuda_deserialize
    device = validate_cuda_device(location)
  File "C:\Users\Administrator\Desktop\SD\stable-diffusion-webui-directml\venv\lib\site-packages\torch\serialization.py", line 166, in validate_cuda_device
    raise RuntimeError('Attempting to deserialize object on a CUDA '
RuntimeError: Attempting to deserialize object on a CUDA device but torch.cuda.is_available() is False. If you are running on a CPU-only machine, please use torch.load with map_location=torch.device('cpu') to map your storages to the CPU.

**Comment by mynameisbill** [comment]
Same problem here. Looks like we need to follow the above instructions: 

"please use torch.load with map_location=torch.device('cpu') to map your storages to the CPU."

I've also found instructions elsewhere advising: 

"It might be enough to add this at the beginning of your code(the line telling PyTorch to use the CPU instead):
device = torch.device("cpu")"

I just have no idea how to implement these instructions. Anyone have more details on how we're supposed to do that?

**Comment by jfranecki** [comment]
What version of torch do you have? You can find that with the `pip show torch` command. Mine is `Version: 2.0.1+cu118`.

**Comment by system3600** [comment]
@jfranecki Version: 2.0.0, without CUDA, I'm trying to run on an AMD video card, would probably work with some torch plugin for directml

**Comment by mynameisbill** [comment]
I just updated to Torch 2.0.1. Still have the same error message. "AssertionError: Torch not compiled with CUDA enabled"

**Comment by vapidvim** [comment]
I was able to fix Vid to Vid error with ChatGPT for my Mac M1/CPU... Open flow_utilis.py and change line 55 to:
RAFT_model.load_state_dict(torch.load(args.model, map_location=torch.device('cpu')))

After than a different error will fire and this is the fix.
Change lines 62-63 to:
frame1_torch = torch.from_numpy(frame1).permute(2, 0, 1).float()[None].to(device)
frame2_torch = torch.from_numpy(frame2).permute(2, 0, 1).float()[None].to(device)

Make sure to restart the terminal after saving.

@volotat, Hope this helps you come up with a solution for the main branch.

**Comment by CaptMorganized** [comment]
Hi There, Im a bit late to the thread , but running into the same error on my m1 16: MacBook while trying to get SD Automatic 1111 running... Im a newbie when it comes to Terminal instructions .. could someone help me with the fix above ?.. ie: explain the line ' open flow_utilis .py ' I tried copying into terminal and nothing ran .. apologies for my ignorance.. any help would be great !!!
