### ISSUE TITLE
Face Crop Option- Yolov5_anime model not loading due to the 'ultralytics' module not being found despite having 'ultralytics' installed.

### ISSUE THREAD

**Issue by Jikelz** [volotat/SD-CN-Animation#164]
Traceback (most recent call last):
  File "D:\AI_ART\Stable Diffusion\stable-diffusion-webui\modules\call_queue.py", line 57, in f
    res = list(func(*args, **kwargs))
  File "D:\AI_ART\Stable Diffusion\stable-diffusion-webui\modules\call_queue.py", line 37, in f
    res = func(*args, **kwargs)
  File "D:\AI_ART\Stable Diffusion\stable-diffusion-webui\modules\img2img.py", line 176, in img2img
    processed = modules.scripts.scripts_img2img.run(p, *args)
  File "D:\AI_ART\Stable Diffusion\stable-diffusion-webui\modules\scripts.py", line 441, in run
    processed = script.run(p, *script_args)
  File "D:\AI_ART\Stable Diffusion\stable-diffusion-webui\extensions\ebsynth_utility\scripts\custom_script.py", line 906, in run
    face_coords = self.detect_face(image, mask_image, face_detection_method, max_crop_size)
  File "D:\AI_ART\Stable Diffusion\stable-diffusion-webui\extensions\ebsynth_utility\scripts\custom_script.py", line 224, in detect_face
    faces = self.detect_anime_face_from_img(img_array)
  File "D:\AI_ART\Stable Diffusion\stable-diffusion-webui\extensions\ebsynth_utility\scripts\custom_script.py", line 187, in detect_anime_face_from_img
    self.anime_face_detector = torch.hub.load('ultralytics/yolov5', 'custom', path=anime_model_path)
  File "D:\AI_ART\Stable Diffusion\stable-diffusion-webui\venv\lib\site-packages\torch\hub.py", line 558, in load
    model = _load_local(repo_or_dir, model, *args, **kwargs)
  File "D:\AI_ART\Stable Diffusion\stable-diffusion-webui\venv\lib\site-packages\torch\hub.py", line 587, in _load_local
    model = entry(*args, **kwargs)
  File "C:\Users\jsh05/.cache\torch\hub\ultralytics_yolov5_master\hubconf.py", line 83, in custom
    return _create(path, autoshape=autoshape, verbose=_verbose, device=device)
  File "C:\Users\jsh05/.cache\torch\hub\ultralytics_yolov5_master\hubconf.py", line 33, in _create
    from models.common import AutoShape, DetectMultiBackend
  File "C:\Users\jsh05/.cache\torch\hub\ultralytics_yolov5_master\models\common.py", line 28, in <module>
    from utils.dataloaders import exif_transpose, letterbox
  File "C:\Users\jsh05/.cache\torch\hub\ultralytics_yolov5_master\utils\dataloaders.py", line 31, in <module>
    from utils.augmentations import (Albumentations, augment_hsv, classify_albumentations, classify_transforms, copy_paste,
  File "C:\Users\jsh05/.cache\torch\hub\ultralytics_yolov5_master\utils\augmentations.py", line 15, in <module>
    from utils.general import LOGGER, check_version, colorstr, resample_segments, segment2box, xywhn2xyxy
  File "C:\Users\jsh05/.cache\torch\hub\ultralytics_yolov5_master\utils\general.py", line 38, in <module>
    from ultralytics.yolo.utils.checks import check_requirements
ModuleNotFoundError: No module named 'ultralytics'

**Comment by Jikelz** [comment]
<img width="1309" alt="Screenshot 2023-06-17 150143" src="https://github.com/volotat/SD-CN-Animation/assets/74120812/2d057c58-258c-439a-ab5e-2c4e519e66fb">
