### ISSUE TITLE
extensions errors in webui1.4.0 version

### ISSUE THREAD

**Issue by mengcius** [volotat/SD-CN-Animation#171]
This plugin causes this problem:
https://github.com/AUTOMATIC1111/stable-diffusion-webui/issues/11448

**Comment by SteveM50** [comment]
this plugin causes errors in many extensions

**Comment by Carlsans** [comment]
Obtained this bug in txt2img tab :  
*** Error completing request
*** Arguments: ('task(qrjs2eyk0pmvvlg)', 'tits', '', [], 20, 0, False, False, 1, 1, 7, -1.0, -1.0, 0, 0, 0, False, 512, 512, False, 0.7, 2, 'Latent', 0, 0, 0, 0, '', '', [], 3, False, False, 'positive', 'comma', 0, False, False, '', 7, 'tits, boobs', [], 0, '', [], 0, '', [], True, False, False, False, 0) {}
    Traceback (most recent call last):
      File "C:\stablediffusionweb\installer\webui\modules\call_queue.py", line 55, in f
        res = list(func(*args, **kwargs))
      File "C:\stablediffusionweb\installer\webui\modules\call_queue.py", line 35, in f
        res = func(*args, **kwargs)
      File "C:\stablediffusionweb\installer\webui\modules\txt2img.py", line 54, in txt2img
        processed = modules.scripts.scripts_txt2img.run(p, *args)
      File "C:\stablediffusionweb\installer\webui\modules\scripts.py", line 456, in run
        processed = script.run(p, *script_args)
    TypeError: Script.run() missing 14 required positional arguments: 'x_type', 'x_values', 'x_values_dropdown', 'y_type', 'y_values', 'y_values_dropdown', 'z_type', 'z_values', 'z_values_dropdown', 'draw_legend', 'include_lone_images', 'include_sub_grids', 'no_fixed_seeds', and 'margin_size'
