### ISSUE TITLE
 bug: TypeError: 'NoneType' object is not iterabl

### ISSUE THREAD

**Issue by xqqcylh6780** [volotat/SD-CN-Animation#184]
**I ran into this problem, please how to solve it：**

*** Error running before_process: E:\sdwebui\stable-diffusion-webui\extensions-builtin\extra-options-section\scripts\extra_options_section.py
    Traceback (most recent call last):
      File "E:\sdwebui\stable-diffusion-webui\modules\scripts.py", line 466, in before_process
        script.before_process(p, *script_args)
      File "E:\sdwebui\stable-diffusion-webui\extensions-builtin\extra-options-section\scripts\extra_options_section.py", line 40, in before_process
        for name, value in zip(self.setting_names, args):
    TypeError: 'NoneType' object is not iterabl
![QQ截图20230725031818](https://github.com/volotat/SD-CN-Animation/assets/60036797/10ebe930-3eea-48b9-bd51-f7ae18a5cf71)

**Comment by CharlesMod** [comment]
+1, I'm getting this as well

**Comment by CharlesMod** [comment]
Fixed it by installing scikit-image:
```
pip install scikit-image==0.19.2 --no-cache-dir
```

**Comment by xqqcylh6780** [comment]
> 通过安装scikit映像来修复它：
> 
> ```
> pip install scikit-image==0.19.2 --no-cache-dir
> ```

I have tried and still reported an error. Can you fix it this way

**Comment by xqqcylh6780** [comment]
> 

I have tried, but it's still this error. Can you fix it this way

**Comment by CharlesMod** [comment]
Hm seems I spoke too soon, I wasn't able to install scikit-image as I intended, building it fails...

**Comment by xqqcylh6780** [comment]
> 嗯，看来我说得太早了，我无法按照我的意图安装 scikit-image，构建它失败了......

But this error doesn't seem to affect it, it should be negligible

**Comment by P-Chao** [comment]
The same error

`*** Error running setup: /home/pengchao/workspace/stable-diffusion-webui-mov2mov/modules/processing_scripts/refiner.py
    Traceback (most recent call last):
      File "/home/pengchao/workspace/stable-diffusion-webui-mov2mov/modules/scripts.py", line 840, in setup_scrips
        script.setup(p, *script_args)
    TypeError: ScriptRefiner.setup() takes 5 positional arguments but 144 were given

---
*** Error running setup: /home/pengchao/workspace/stable-diffusion-webui-mov2mov/modules/processing_scripts/seed.py
    Traceback (most recent call last):
      File "/home/pengchao/workspace/stable-diffusion-webui-mov2mov/modules/scripts.py", line 840, in setup_scrips
        script.setup(p, *script_args)
    TypeError: ScriptSeed.setup() takes 8 positional arguments but 144 were given

---
*** Error running before_process: /home/pengchao/workspace/stable-diffusion-webui-mov2mov/extensions-builtin/extra-options-section/scripts/extra_options_section.py
    Traceback (most recent call last):
      File "/home/pengchao/workspace/stable-diffusion-webui-mov2mov/modules/scripts.py", line 710, in before_process
        script.before_process(p, *script_args)
      File "/home/pengchao/workspace/stable-diffusion-webui-mov2mov/extensions-builtin/extra-options-section/scripts/extra_options_section.py", line 63, in before_process
        for name, value in zip(self.setting_names, args):
    TypeError: 'NoneType' object is not iterable

---`
