### ISSUE TITLE
FileNotFoundError

### ISSUE THREAD

**Issue by Alicequinz** [volotat/SD-CN-Animation#192]
Downloading: "https://drive.google.com/uc?id=1-UYsTXkdUkHLgtPK1Y5_7kKzCgzL_Z6o" to C:\Users\User\\.cache\torch\hub\checkpoints\models\FloweR\FloweR_0.1.2.pth

An exception occurred while trying to process the frame: [Errno 2] No such file or directory: 'C:\\Users\\User\\.cache\\torch\\hub\\checkpoints\\models\\FloweR\\tmpow56oykh'
Traceback (most recent call last):
  File "B:\StableDiffusion\automatic\extensions\SD-CN-Animation\scripts\base_ui.py", line 146, in process
    yield from txt2vid.start_process(*args)
  File "B:\StableDiffusion\automatic\extensions\SD-CN-Animation\scripts\core\txt2vid.py", line 139, in start_process
    FloweR_load_model(size[0], size[1])
  File "B:\StableDiffusion\automatic\extensions\SD-CN-Animation\scripts\core\txt2vid.py", line 40, in FloweR_load_model
    load_file_from_url(remote_model_path, file_name=model_path)
  File "B:\StableDiffusion\automatic\venv\lib\site-packages\basicsr\utils\download_util.py", line 98, in load_file_from_url
    download_url_to_file(url, cached_file, hash_prefix=None, progress=progress)
  File "B:\StableDiffusion\automatic\venv\lib\site-packages\torch\hub.py", line 625, in download_url_to_file
    f = tempfile.NamedTemporaryFile(delete=False, dir=dst_dir)
  File "C:\Users\User\AppData\Local\Programs\Python\Python310\lib\tempfile.py", line 559, in NamedTemporaryFile
    file = _io.open(dir, mode, buffering=buffering,
  File "C:\Users\User\AppData\Local\Programs\Python\Python310\lib\tempfile.py", line 556, in opener
    fd, name = _mkstemp_inner(dir, prefix, suffix, flags, output_type)
  File "C:\Users\User\AppData\Local\Programs\Python\Python310\lib\tempfile.py", line 256, in _mkstemp_inner
    fd = _os.open(file, flags, 0o600)
FileNotFoundError: [Errno 2] No such file or directory: 'C:\\Users\\User\\.cache\\torch\\hub\\checkpoints\\models\\FloweR\\tmpow56oykh'

**Any fix for this error?**

**Comment by K1lly76** [comment]
I answered the problem here: https://github.com/volotat/SD-CN-Animation/issues/195
