### ISSUE TITLE
SD-CN-Animation base_ui.py error

### ISSUE THREAD

**Issue by itsidleboy** [volotat/SD-CN-Animation#194]
Python 3.10.11 (tags/v3.10.11:7d4cc5a, Apr  5 2023, 00:38:17) [MSC v.1929 64 bit (AMD64)]
Version: 1.6.0
Commit hash: <none>
Installing SD-CN-Animation requirement: scikit-image
Checking roop requirements
Install insightface==0.7.3
Installing sd-webui-roop requirement: insightface==0.7.3
Install onnx==1.14.0
Installing sd-webui-roop requirement: onnx==1.14.0
Install onnxruntime==1.15.0
Installing sd-webui-roop requirement: onnxruntime==1.15.0
Install opencv-python==4.7.0.72
Installing sd-webui-roop requirement: opencv-python==4.7.0.72
Launching Web UI with arguments: --medvram --xformers --skip-python-version-check
D:\Rahul\StabilityMatrix\data\Packages\stable-diffusion-webui\venv\lib\site-packages\torchaudio\backend\utils.py:74: UserWarning: No audio backend is available.
  warnings.warn("No audio backend is available.")
*** Error loading script: base_ui.py
    Traceback (most recent call last):
      File "D:\Rahul\StabilityMatrix\data\Packages\stable-diffusion-webui\modules\scripts.py", line 382, in load_scripts
        script_module = script_loading.load_module(scriptfile.path)
      File "D:\Rahul\StabilityMatrix\data\Packages\stable-diffusion-webui\modules\script_loading.py", line 10, in load_module
        module_spec.loader.exec_module(module)
      File "<frozen importlib._bootstrap_external>", line 883, in exec_module
      File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
      File "D:\Rahul\StabilityMatrix\data\Packages\stable-diffusion-webui\extensions\SD-CN-Animation\scripts\base_ui.py", line 9, in <module>
        from webui import wrap_gradio_gpu_call
    ImportError: cannot import name 'wrap_gradio_gpu_call' from 'webui' (D:\Rahul\StabilityMatrix\data\Packages\stable-diffusion-webui\webui.py)

---
2023-09-14 16:10:22,098 - roop - INFO - roop v0.0.2
2023-09-14 16:10:22,148 - roop - INFO - roop v0.0.2
Loading weights [e6415c4892] from D:\Rahul\StabilityMatrix\data\Packages\stable-diffusion-webui\models\Stable-diffusion\realisticVisionV20_v20.safetensors
D:\Rahul\StabilityMatrix\data\Packages\stable-diffusion-webui\extensions\sd-webui-roop\scripts\faceswap.py:38: GradioDeprecationWarning: Usage of gradio.inputs is deprecated, and will not be supported in the future, please import your component from gradio.components
  img = gr.inputs.Image(type="pil")
D:\Rahul\StabilityMatrix\data\Packages\stable-diffusion-webui\modules\gradio_extensons.py:25: GradioDeprecationWarning: `optional` parameter is deprecated, and it has no effect
  res = original_IOComponent_init(self, *args, **kwargs)
D:\Rahul\StabilityMatrix\data\Packages\stable-diffusion-webui\extensions\sd-webui-roop\scripts\faceswap.py:55: GradioDeprecationWarning: Usage of gradio.inputs is deprecated, and will not be supported in the future, please import your component from gradio.components
  upscaler_name = gr.inputs.Dropdown(
D:\Rahul\StabilityMatrix\data\Packages\stable-diffusion-webui\extensions\sd-webui-roop\scripts\faceswap.py:74: GradioDeprecationWarning: Usage of gradio.inputs is deprecated, and will not be supported in the future, please import your component from gradio.components
  model = gr.inputs.Dropdown(
Running on local URL:  http://127.0.0.1:7860

To create a public link, set `share=True` in `launch()`.
Creating model from config: D:\Rahul\StabilityMatrix\data\Packages\stable-diffusion-webui\configs\v1-inference.yaml
Startup time: 16.3s (prepare environment: 10.4s, import torch: 2.3s, import gradio: 0.7s, setup paths: 0.6s, initialize shared: 0.2s, other imports: 0.4s, load scripts: 1.0s, create ui: 0.3s, gradio launch: 0.5s).
Applying attention optimization: xformers... done.

**Comment by Garin2-colab** [comment]
i added these two lines in ui.py file at \stable-diffusion-webui\modules\

def create_sampler_and_steps_selection(choices, tabname):
    return scripts.scripts_txt2img.script('Sampler').steps, scripts.scripts_txt2img.script('Sampler').sampler_name
