### ISSUE TITLE
[BUG] Error i think could be wrong thought 

### ISSUE THREAD

**Issue by NullEqualsZero** [volotat/SD-CN-Animation#203]
Whenever I hit generate (on vid2vid, I haven't tried txt2vid yet) I get the following error. What should I do?
*** Error running setup: D:\stable-diffusion-webui\modules/processing_scripts\refiner.py
    Traceback (most recent call last):
      File "D:\stable-diffusion-webui\modules\scripts.py", line 741, in setup_scrips
        script.setup(p, *script_args)
    TypeError: ScriptRefiner.setup() takes 5 positional arguments but 222 were given

---
*** Error running setup: D:\stable-diffusion-webui\modules/processing_scripts\seed.py
    Traceback (most recent call last):
      File "D:\stable-diffusion-webui\modules\scripts.py", line 741, in setup_scrips
        script.setup(p, *script_args)
    TypeError: ScriptSeed.setup() takes 8 positional arguments but 222 were given

---
*** Error running before_process: D:\stable-diffusion-webui\extensions-builtin\extra-options-section\scripts\extra_options_section.py
    Traceback (most recent call last):
      File "D:\stable-diffusion-webui\modules\scripts.py", line 611, in before_process
        script.before_process(p, *script_args)
      File "D:\stable-diffusion-webui\extensions-builtin\extra-options-section\scripts\extra_options_section.py", line 62, in before_process
        for name, value in zip(self.setting_names, args):
    TypeError: 'NoneType' object is not iterable

**Comment by physeo** [comment]
+1 Same exact errors on my end.
Intel Core i7-9700k
RTX 3090
32GB RAM

**Comment by keithbandit98** [comment]
me too

**Comment by aniruddhahar** [comment]
It seems this extension is breaking every other extension when it's enabled.

**Comment by psdsam-NiuNiuKing** [comment]
+1

**Comment by ricardofeynman** [comment]
While this may not be the answer you all are looking for, if you want it to work, get yourself a fresh install of A1111 1.2.0 https://github.com/AUTOMATIC1111/stable-diffusion-webui/tree/v1.2.0 and then grab https://github.com/volotat/SD-CN-Animation/tree/eddf1a4c8fb327e4fca05821490f20d97945ac7e Only install the relevant extensions you need, don't update anything (I have used a very recent commit of the ControlNet extension without issue), and keep this install dedicated to SD-CN Animation.

Not so many breaking errors thrown with this combination I find, and best results for certain models also. Have fun everybody ;)

**Comment by 1manfactory** [comment]
Same with me

> *** Error running setup: C:\sd.webui\webui\modules/processing_scripts\refiner.py███████| 15/15 [00:21<00:00,  1.50s/it]
    Traceback (most recent call last):
      File "C:\sd.webui\webui\modules\scripts.py", line 938, in setup_scrips
        script.setup(p, *script_args)
    TypeError: ScriptRefiner.setup() takes 5 positional arguments but 247 were given

---
*** Error running setup: C:\sd.webui\webui\modules/processing_scripts\seed.py
    Traceback (most recent call last):
      File "C:\sd.webui\webui\modules\scripts.py", line 938, in setup_scrips
        script.setup(p, *script_args)
    TypeError: ScriptSeed.setup() takes 8 positional arguments but 247 were given

---
*** Error running before_process: C:\sd.webui\webui\extensions-builtin\extra-options-section\scripts\extra_options_section.py
    Traceback (most recent call last):
      File "C:\sd.webui\webui\modules\scripts.py", line 776, in before_process
        script.before_process(p, *script_args)
      File "C:\sd.webui\webui\extensions-builtin\extra-options-section\scripts\extra_options_section.py", line 63, in before_process
        for name, value in zip(self.setting_names, args):
    TypeError: 'NoneType' object is not iterable

---
*** Error running process: C:\sd.webui\webui\extensions-builtin\soft-inpainting\scripts\soft_inpainting.py
    Traceback (most recent call last):
      File "C:\sd.webui\webui\modules\scripts.py", line 784, in process
        script.process(p, *script_args)
    TypeError: Script.process() takes 9 positional arguments but 247 were given

---
