### ISSUE TITLE
txt2vid doesn't work at all

### ISSUE THREAD

**Issue by Troceleng** [volotat/SD-CN-Animation#209]
I put in settings, click "Generate" and after two frames, I get this:

An exception occurred while trying to process the frame: 'NoneType' object has no attribute 'width'
Traceback (most recent call last):
  File "G:\PORTABLE_SOFTWARE\AI\stable-diffusion-webui-forge\webui\extensions\SD-CN-Animation\scripts\base_ui.py", line 146, in process
    yield from txt2vid.start_process(*args)
  File "G:\PORTABLE_SOFTWARE\AI\stable-diffusion-webui-forge\webui\extensions\SD-CN-Animation\scripts\core\txt2vid.py", line 199, in start_process
    processed_frames, _, _, _ = utils.img2img(args_dict)
  File "G:\PORTABLE_SOFTWARE\AI\stable-diffusion-webui-forge\webui\extensions\SD-CN-Animation\scripts\core\utils.py", line 319, in img2img
    generated_images = process_img(p, image, None, '', args.script_inputs)
  File "G:\PORTABLE_SOFTWARE\AI\stable-diffusion-webui-forge\webui\extensions\SD-CN-Animation\scripts\core\utils.py", line 203, in process_img
    proc = process_images(p)
  File "G:\PORTABLE_SOFTWARE\AI\stable-diffusion-webui-forge\webui\modules\processing.py", line 749, in process_images
    res = process_images_inner(p)
  File "G:\PORTABLE_SOFTWARE\AI\stable-diffusion-webui-forge\webui\modules\processing.py", line 1010, in process_images_inner
    original_denoised_image = uncrop(original_denoised_image, (overlay_image.width, overlay_image.height), p.paste_to)
AttributeError: 'NoneType' object has no attribute 'width'

No help found online to tell me what the actual problem is and more importantly, how to fix it.

**Comment by Johnnyprim3** [comment]
I'm using it right now...
To get it to work, switch back to Web UI version: v1.7.0

**Comment by KintCark** [comment]
I did but it's still not working

**Comment by titlestad** [comment]
Somebody probably deprecated something important because they are lazy.
