### ISSUE TITLE
[Bug] AttributeError: 'str' object has no attribute '__dict__'

### ISSUE THREAD

**Issue by ke1ne** [volotat/SD-CN-Animation#29]
Getting this with vid2vid. v0.6 + https://github.com/vladmandic/automatic:
```
override_settings: []
Traceback (most recent call last):
  File "e:\.ai\automatic\venv\lib\site-packages\gradio\routes.py", line 399, in run_predict
    output = await app.get_blocks().process_api(
  File "e:\.ai\automatic\venv\lib\site-packages\gradio\blocks.py", line 1299, in process_api
    result = await self.call_function(
  File "e:\.ai\automatic\venv\lib\site-packages\gradio\blocks.py", line 1036, in call_function
    prediction = await anyio.to_thread.run_sync(
  File "e:\.ai\automatic\venv\lib\site-packages\anyio\to_thread.py", line 31, in run_sync
    return await get_asynclib().run_sync_in_worker_thread(
  File "e:\.ai\automatic\venv\lib\site-packages\anyio\_backends\_asyncio.py", line 937, in run_sync_in_worker_thread
    return await future
  File "e:\.ai\automatic\venv\lib\site-packages\anyio\_backends\_asyncio.py", line 867, in run
    result = context.run(func, *args)
  File "e:\.ai\automatic\venv\lib\site-packages\gradio\utils.py", line 488, in async_iteration
    return next(iterator)
  File "e:\.ai\automatic/extensions/sd-cn-animation/scripts\vid2vid.py", line 172, in start_process
    processed_frames, _, _, _ = img2img(args_dict)
  File "e:\.ai\automatic/extensions/sd-cn-animation/scripts\vid2vid.py", line 445, in img2img
    print('script_inputs 1:', args.script_inputs[1].__dict__)
AttributeError: 'str' object has no attribute '__dict__'
```

**Comment by alexfredo** [comment]
Yeah I have the same error

**Comment by volotat** [comment]
For now only Automatic1111/wub-ui is supported. But I tried to fix this issue anyway. Please, update the extension and try to run it again. Tell me if it works for you.

**Comment by ke1ne** [comment]
With new version, got this:
```
Traceback (most recent call last):
  File "e:\.ai\automatic\venv\lib\site-packages\gradio\routes.py", line 399, in run_predict
    output = await app.get_blocks().process_api(
  File "e:\.ai\automatic\venv\lib\site-packages\gradio\blocks.py", line 1299, in process_api
    result = await self.call_function(
  File "e:\.ai\automatic\venv\lib\site-packages\gradio\blocks.py", line 1036, in call_function
    prediction = await anyio.to_thread.run_sync(
  File "e:\.ai\automatic\venv\lib\site-packages\anyio\to_thread.py", line 31, in run_sync
    return await get_asynclib().run_sync_in_worker_thread(
  File "e:\.ai\automatic\venv\lib\site-packages\anyio\_backends\_asyncio.py", line 937, in run_sync_in_worker_thread
    return await future
  File "e:\.ai\automatic\venv\lib\site-packages\anyio\_backends\_asyncio.py", line 867, in run
    result = context.run(func, *args)
  File "e:\.ai\automatic\venv\lib\site-packages\gradio\utils.py", line 488, in async_iteration
    return next(iterator)
  File "e:\.ai\automatic/extensions/sd-cn-animation/scripts\vid2vid.py", line 172, in start_process
    processed_frames, _, _, _ = img2img(args_dict)
  File "e:\.ai\automatic/extensions/sd-cn-animation/scripts\vid2vid.py", line 445, in img2img
    if shared.cmd_opts.enable_console_prompts:
AttributeError: 'Namespace' object has no attribute 'enable_console_prompts'
```

**Comment by alexfredo** [comment]
For me it's works now but the file is not save in the vid2vid folder I have no idea where is the video

**Comment by volotat** [comment]
@ke1ne I just took a closer look at how img2img is implemented in Automatic1111 and vladmandic fork. It seems that this is just a legacy code that I borrowed, and everything should work fine without it. Although there are probably still some surprises like that left. Updated the code ones again.

@alexfredo So it did create 'outputs/sd-cn-animation/vid2vid/' folder but does not saved the video? If so this is quite strange.

**Comment by alexfredo** [comment]
Yes the folder are created but not the video I have checked the temp folder of my computer there's just the original video in a new folder

**Comment by volotat** [comment]
@alexfredo I think I got this. I used time of creation as a filename and apparently colon is a forbidden character in the filename on windows. Check it out again please.

**Comment by ke1ne** [comment]
Thanks! It started to generate, and on some stage I got this:
```
Traceback (most recent call last):
  File "e:\.ai\automatic\venv\lib\site-packages\gradio\routes.py", line 399, in run_predict
    output = await app.get_blocks().process_api(
  File "e:\.ai\automatic\venv\lib\site-packages\gradio\blocks.py", line 1299, in process_api
    result = await self.call_function(
  File "e:\.ai\automatic\venv\lib\site-packages\gradio\blocks.py", line 1036, in call_function
    prediction = await anyio.to_thread.run_sync(
  File "e:\.ai\automatic\venv\lib\site-packages\anyio\to_thread.py", line 31, in run_sync
    return await get_asynclib().run_sync_in_worker_thread(
  File "e:\.ai\automatic\venv\lib\site-packages\anyio\_backends\_asyncio.py", line 937, in run_sync_in_worker_thread
    return await future
  File "e:\.ai\automatic\venv\lib\site-packages\anyio\_backends\_asyncio.py", line 867, in run
    result = context.run(func, *args)
  File "e:\.ai\automatic\venv\lib\site-packages\gradio\utils.py", line 488, in async_iteration
    return next(iterator)
  File "e:\.ai\automatic/extensions/sd-cn-animation/scripts\vid2vid.py", line 172, in start_process
    processed_frames, _, _, _ = img2img(args_dict)
  File "e:\.ai\automatic/extensions/sd-cn-animation/scripts\vid2vid.py", line 470, in img2img
    if opts.samples_log_stdout:
  File "E:\.ai\automatic\modules\shared.py", line 506, in __getattr__
    return super(Options, self).__getattribute__(item)
AttributeError: 'Options' object has no attribute 'samples_log_stdout'
```

I think, it's similar case related to non-existing parameters, etc. The samples_log_stdout parameter appears in the scripts/vid2vid.py too, and there is an IF check too.

**Comment by alexfredo** [comment]
@volotat yes it's works now ! thanks

**Comment by ke1ne** [comment]
Deleted these lines in SD-CN-Animation\scripts\vid2vid.py, and it started to work:
```
    if opts.samples_log_stdout:
        print(generation_info_js)
```

P.S. I would propose to disable the Generate button while the actually generates. Or replace it to Stop.

**Comment by volotat** [comment]
@ke1ne Yep. Exactly the same thing. Removed this code also.

Regarding the buttons, I totally agree. My closest plans are to add txt2vid mode, add 'interrupt' button, disable 'generate' while it's running and make all model dependencies to download automatically.

**Comment by ke1ne** [comment]
@volotat BTW, who is Crimea belongs?

**Comment by volotat** [comment]
> @volotat BTW, who is Crimea belongs to?
"On 16 March 2018, the case Satter v. Department of Justice was closed"

**Comment by ke1ne** [comment]
@volotat well, can't have a deal with the ruschism supporter. no good wishes

**Comment by volotat** [comment]
@ke1ne Far from it. Just google it. I hope you will understand what I'm trying to say. As I have a lot to say about it, but this is not the best place for it.
