### ISSUE TITLE
Gradio error on generation

### ISSUE THREAD

**Issue by Tenoke** [volotat/SD-CN-Animation#31]
Happens on both vid2vid and textvid after clicking 'Generate'.

```Traceback (most recent call last):
  File "/content/sd/lib/python3.10/site-packages/gradio/routes.py", line 337, in run_predict
    output = await app.get_blocks().process_api(
  File "/content/sd/lib/python3.10/site-packages/gradio/blocks.py", line 1015, in process_api
    result = await self.call_function(
  File "/content/sd/lib/python3.10/site-packages/gradio/blocks.py", line 843, in call_function
    raise ValueError("Need to enable queue to use generators.")
ValueError: Need to enable queue to use generators.
```
![image](https://user-images.githubusercontent.com/1922868/236705594-8ca8ec10-88e5-4ed0-8607-d7dcc97b9be2.png)

**Comment by volotat** [comment]
Are you using Automatic1111/webui or any other webui fork? The error states that queue is not enabled, but ui of the extension does enable queue at it's ui code. I also would recommend trying to update webui to the latest version. Please tell me if it works for you.

**Comment by Tenoke** [comment]
I upgraded webui and now I can get vid2vid to work, in txt2vid it only generates 2 frames. I do get this error in both but it seems likely it's due to something in my setup.

```
Error running process: /content/stable-diffusion-webui/extensions/stable-diffusion-webui-two-shot/scripts/two_shot.py
Traceback (most recent call last):
  File "/content/stable-diffusion-webui/modules/scripts.py", line 417, in process
    script.process(p, *script_args)
  File "/content/stable-diffusion-webui/extensions/stable-diffusion-webui-two-shot/scripts/two_shot.py", line 557, in process
    enabled, raw_divisions, raw_positions, raw_weights, raw_end_at_step, alpha_blend, *cur_weight_sliders = args
ValueError: not enough values to unpack (expected at least 6, got 0)

Error running process_batch: /content/stable-diffusion-webui/extensions/sd-webui-additional-networks/scripts/additional_networks.py
Traceback (most recent call last):
  File "/content/stable-diffusion-webui/modules/scripts.py", line 435, in process_batch
    script.process_batch(p, *script_args, **kwargs)
  File "/content/stable-diffusion-webui/extensions/sd-webui-additional-networks/scripts/additional_networks.py", line 189, in process_batch
    if not args[0]:
IndexError: tuple index out of range
```

I can only find the completed video in the folders rather than in the UI, not sure if that's related to the errors. There are vids for the txt2vid part in the folders but they are 1s long and I dont see a way to request more frames in the UI to try if it works for a longer video.

**Comment by volotat** [comment]
@Tenoke Please, try also updating the ControlNet extension.

**Comment by Tenoke** [comment]
@volotat I just removed and reinstalled it (and confirmed it works) but I get the same error (and only 1 frame) on text2vid

```
Error running process: /content/stable-diffusion-webui/extensions/stable-diffusion-webui-two-shot/scripts/two_shot.py
Traceback (most recent call last):
  File "/content/stable-diffusion-webui/modules/scripts.py", line 417, in process
    script.process(p, *script_args)
  File "/content/stable-diffusion-webui/extensions/stable-diffusion-webui-two-shot/scripts/two_shot.py", line 557, in process
    enabled, raw_divisions, raw_positions, raw_weights, raw_end_at_step, alpha_blend, *cur_weight_sliders = args
ValueError: not enough values to unpack (expected at least 6, got 0)

Error running process_batch: /content/stable-diffusion-webui/extensions/sd-webui-additional-networks/scripts/additional_networks.py
Traceback (most recent call last):
  File "/content/stable-diffusion-webui/modules/scripts.py", line 435, in process_batch
    script.process_batch(p, *script_args, **kwargs)
  File "/content/stable-diffusion-webui/extensions/sd-webui-additional-networks/scripts/additional_networks.py", line 189, in process_batch
    if not args[0]:
IndexError: tuple index out of range
```

**Comment by Azevs** [comment]
> @Tenoke Please, try also updating the ControlNet extension.

I also have this "Need to enable queue to use generators" error. Just updated everything, still persists. Any other ideas on how to solve it?

**Comment by Tenoke** [comment]
> > @Tenoke Please, try also updating the ControlNet extension.
> 
> I also have this "Need to enable queue to use generators" error. Just updated everything, still persists. Any other ideas on how to solve it?

If you have everything upgraded also make sure you are starting webui with the --gradio-queue flag e.g.

```python launch.py --listen --xformers --enable-insecure-extension-access --theme dark --gradio-queue --multiple```

**Comment by Azevs** [comment]
> > > @Tenoke Please, try also updating the ControlNet extension.
> > 
> > 
> > I also have this "Need to enable queue to use generators" error. Just updated everything, still persists. Any other ideas on how to solve it?
> 
> If you have everything upgraded also make sure you are starting webui with the --gradio-queue flag e.g.
> 
> `python launch.py --listen --xformers --enable-insecure-extension-access --theme dark --gradio-queue --multiple`

Thank you, Tenoke!

Now I have this when I try to generate something:

ValueError: Query/Key/Value should all have the same dtype
  query.dtype: torch.float32
  key.dtype  : torch.float32
  value.dtype: torch.float16

**Comment by Apatiste** [comment]
> python launch.py --listen --xformers --enable-insecure-extension-access --theme dark --gradio-queue --multiple

Where do you exactly put these commands ? 
Is it in the webui_user.bat or launch.py ?

**Comment by Azevs** [comment]
> > python launch.py --listen --xformers --enable-insecure-extension-access --theme dark --gradio-queue --multiple
> 
> Where do you exactly put these commands ? Is it in the webui_user.bat or launch.py ?

I edited webui.bat, but I am not sure if it was the right way to do it

**Comment by Tenoke** [comment]
> > python launch.py --listen --xformers --enable-insecure-extension-access --theme dark --gradio-queue --multiple
> 
> Where do you exactly put these commands ? Is it in the webui_user.bat or launch.py ?

I don't know how you start it, I start it by running the command above direclty. As in those flags go after launch.py. If you have 'python launch.py' in that .bat then yeah just add it there.

**Comment by Apatiste** [comment]
Thanks, I will try it out.

**Comment by VladislavNedodaiev** [comment]
> I've the latest version of the webui, I wonder if, perhaps, the -medvram option is incompatible with this extension.
> 
> I tried as well the --gradio-queue command, I ended up with another error code, TypeError: Button.update() got an unexpected keyword argument 'interactive'

@Apatiste I don't use any additional commands. Neither the medvram or gradio-queue, just what comes out of the box from A1111 webui repository. Try removing those commands to see if this helps.

**Comment by dungtran183** [comment]
> > @Tenoke perhaps you have outdated A1111 webui. I had the same issue which is now gone after I've updated webui to the latest version
> 
> I've the latest version of the webui, I wonder if, perhaps, the -medvram option is incompatible with this extension.
> 
> I tried as well the --gradio-queue command, I ended up with another error code, TypeError: Button.update() got an unexpected keyword argument 'interactive'

I got exactly the same error as yours. The first one is: "ValueError: Need to enable queue to use generators.", after adding "--gradio-queue" it leads to " TypeError: Button.update() got an unexpected keyword argument 'interactive'". Everyone, please give a clear solution for this error.

**Comment by wyliefoxxx** [comment]
Can be fixed by removing every single occurrence of 'interactive=False' within the gradio button references in the txt2vid.py script

gr.Button.update(interactive=False)   change to   gr.Button.update()

<base sd-webui-dir>/extensions/SD-CN-Animation/scripts/core/txt2vid.py

**Comment by rugabunda** [comment]
I had --no-gradio-queue in webui.bat, removing this line, and or, replacing it with --gradio-queue fixed this problem.
