### ISSUE TITLE
Error generating Vid2Vid 

### ISSUE THREAD

**Issue by ameen-roayan** [volotat/SD-CN-Animation#34]
Hello, 

I am getting this error and i am not sure what i am missing, made sure of input size, folder locations and everything, running it through a1111

Already up to date.
venv "F:\AI\Automatic1111\stable-diffusion-webui\venv\Scripts\Python.exe"
Python 3.10.5 (tags/v3.10.5:f377153, Jun  6 2022, 16:14:13) [MSC v.1929 64 bit (AMD64)]
Commit hash: 5ab7f213bec2f816f9c5644becb32eb72c8ffb89
Installing requirements
[Auto-Photoshop-SD] Attempting auto-update...
[Auto-Photoshop-SD] switch branch to extension branch.
checkout_result: Your branch is up to date with 'origin/master'.

[Auto-Photoshop-SD] Current Branch.
branch_result: * master

[Auto-Photoshop-SD] Fetch upstream.
fetch_result:
[Auto-Photoshop-SD] Pull upstream.
pull_result: Already up to date.

Installing SD-CN-Animation requirement: scikit-image==0.19.2

Installing requirements for TemporalKit extension

Launching Web UI with arguments: --opt-sdp-attention --api
No module 'xformers'. Proceeding without it.
python_server_full_path:  F:\AI\Automatic1111\stable-diffusion-webui\extensions\Auto-Photoshop-StableDiffusion-Plugin\server/python_server
Civitai Helper: Get Custom Model Folder
Civitai Helper: Load setting from: F:\AI\Automatic1111\stable-diffusion-webui\extensions\Stable-Diffusion-Webui-Civitai-Helper\setting.json
Civitai Helper: No setting file, use default
Better Prompt version is v0.2.0
ControlNet v1.1.150
ControlNet v1.1.150
Loading weights [d10ad6063d] from F:\AI\Automatic1111\stable-diffusion-webui\models\Stable-diffusion\unvailAI3DKXV2_3dkxV2.safetensors
Creating model from config: F:\AI\Automatic1111\stable-diffusion-webui\configs\v1-inference.yaml
LatentDiffusion: Running in eps-prediction mode
DiffusionWrapper has 859.52 M params.
Loading VAE weights specified in settings: F:\AI\Automatic1111\stable-diffusion-webui\models\VAE\vae-ft-mse-840000-ema-pruned.ckpt
Applying scaled dot product cross attention optimization.
Textual inversion embeddings loaded(4): amouranth, beauty512, CharTurner, neg_realism512
Textual inversion embeddings skipped(5): 21charturnerv2, nartfixer, nfixer, nrealfixer, rz-neg-general
Removing ToMe patch (if exists)
Model loaded in 2.3s (create model: 0.2s, apply weights to model: 0.3s, apply half(): 0.4s, load VAE: 0.2s, move model to device: 0.4s, load textual inversion embeddings: 0.7s).
Running on local URL:  http://127.0.0.1:7860

To create a public link, set `share=True` in `launch()`.
Startup time: 9.8s (import torch: 1.0s, import gradio: 0.8s, import ldm: 0.3s, other imports: 0.5s, list SD models: 0.1s, load scripts: 1.9s, load SD checkpoint: 2.4s, create ui: 2.5s, gradio launch: 0.1s).
Consuming a byte in the end state
Consuming a byte in the end state
controlnet batch mode
Loading model: control_sd15_hed [fef5e48e]
Loaded state_dict from [F:\AI\Automatic1111\stable-diffusion-webui\extensions\sd-webui-controlnet\models\control_sd15_hed.pth]
Loading config: F:\AI\Automatic1111\stable-diffusion-webui\extensions\sd-webui-controlnet\models\control_sd15_hed.yaml
ControlNet model control_sd15_hed [fef5e48e] loaded.
Error running process: F:\AI\Automatic1111\stable-diffusion-webui\extensions\sd-webui-controlnet\scripts\controlnet.py
Traceback (most recent call last):
  File "F:\AI\Automatic1111\stable-diffusion-webui\modules\scripts.py", line 417, in process
    script.process(p, *script_args)
  File "F:\AI\Automatic1111\stable-diffusion-webui\extensions\sd-webui-controlnet\scripts\controlnet.py", line 1035, in process
    input_image = HWC3(image['image'])
  File "F:\AI\Automatic1111\stable-diffusion-webui\extensions\sd-webui-controlnet\annotator\util.py", line 6, in HWC3
    assert x.dtype == np.uint8
  File "F:\AI\Automatic1111\stable-diffusion-webui\venv\lib\site-packages\PIL\Image.py", line 529, in __getattr__
    raise AttributeError(name)
AttributeError: dtype

**Comment by ameen-roayan** [comment]
Yeah that happens on batch, and the other methods as well. text2image does work however

**Comment by ameen-roayan** [comment]
100%|██████████████████████████████████████████████████████████████████████████████████| 15/15 [00:02<00:00,  5.68it/s]
Traceback (most recent call last):
  File "F:\AI\Automatic1111\stable-diffusion-webui\venv\lib\site-packages\gradio\routes.py", line 399, in run_predict
    output = await app.get_blocks().process_api(
  File "F:\AI\Automatic1111\stable-diffusion-webui\venv\lib\site-packages\gradio\blocks.py", line 1299, in process_api
    result = await self.call_function(
  File "F:\AI\Automatic1111\stable-diffusion-webui\venv\lib\site-packages\gradio\blocks.py", line 1036, in call_function
    prediction = await anyio.to_thread.run_sync(
  File "F:\AI\Automatic1111\stable-diffusion-webui\venv\lib\site-packages\anyio\to_thread.py", line 31, in run_sync
    return await get_asynclib().run_sync_in_worker_thread(
  File "F:\AI\Automatic1111\stable-diffusion-webui\venv\lib\site-packages\anyio\_backends\_asyncio.py", line 937, in run_sync_in_worker_thread
    return await future
  File "F:\AI\Automatic1111\stable-diffusion-webui\venv\lib\site-packages\anyio\_backends\_asyncio.py", line 867, in run
    result = context.run(func, *args)
  File "F:\AI\Automatic1111\stable-diffusion-webui\venv\lib\site-packages\gradio\utils.py", line 488, in async_iteration
    return next(iterator)
  File "F:\AI\Automatic1111\stable-diffusion-webui\extensions\SD-CN-Animation\scripts\base_ui.py", line 121, in process
    yield from vid2vid.start_process(*args)
  File "F:\AI\Automatic1111\stable-diffusion-webui/extensions/sd-cn-animation/scripts\core\vid2vid.py", line 113, in start_process
    processed_frames, _, _, _ = utils.img2img(args_dict)
  File "F:\AI\Automatic1111\stable-diffusion-webui/extensions/sd-cn-animation/scripts\core\utils.py", line 297, in img2img
    generated_images = process_img(p, image, None, '', args.script_inputs)
  File "F:\AI\Automatic1111\stable-diffusion-webui/extensions/sd-cn-animation/scripts\core\utils.py", line 182, in process_img
    generated_images.append(proc.images[0])
IndexError: list index out of range

This secondary error procs after the first one
