### ISSUE TITLE
Several errors when running txt2vid, video generated fine

### ISSUE THREAD

**Issue by alexopus** [volotat/SD-CN-Animation#54]
Using default settings and prompt "lemon" after installing the extension, updating automatic1111 and all my extensions and restarting everything:

```
100%|████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 6/6 [00:03<00:00,  1.99it/s]
Error running postprocess_batch: D:\stable-diffusion-webui\extensions\multidiffusion-upscaler-for-automatic1111\scripts\tilediffusion.py█████████| 6/6 [00:02<00:00,  2.70it/s]
Traceback (most recent call last):
  File "D:\stable-diffusion-webui\modules\scripts.py", line 453, in postprocess_batch
    script.postprocess_batch(p, *script_args, images=images, **kwargs)
TypeError: Script.postprocess_batch() missing 1 required positional argument: 'enabled'

Error running postprocess_batch: D:\stable-diffusion-webui\extensions\sd-dynamic-thresholding\scripts\dynamic_thresholding.py
Traceback (most recent call last):
  File "D:\stable-diffusion-webui\modules\scripts.py", line 453, in postprocess_batch
    script.postprocess_batch(p, *script_args, images=images, **kwargs)
TypeError: Script.postprocess_batch() missing 8 required positional arguments: 'enabled', 'mimic_scale', 'threshold_percentile', 'mimic_mode', 'mimic_scale_min', 'cfg_mode', 'cfg_scale_min', and 'powerscale_power'

Error running postprocess: D:\stable-diffusion-webui\extensions\multidiffusion-upscaler-for-automatic1111\scripts\tilediffusion.py
Traceback (most recent call last):
  File "D:\stable-diffusion-webui\modules\scripts.py", line 444, in postprocess
    script.postprocess(p, processed, *script_args)
TypeError: Script.postprocess() missing 1 required positional argument: 'enabled'

Error running postprocess: D:\stable-diffusion-webui\extensions\multidiffusion-upscaler-for-automatic1111\scripts\vae_optimize.py
Traceback (most recent call last):
  File "D:\stable-diffusion-webui\modules\scripts.py", line 444, in postprocess
    script.postprocess(p, processed, *script_args)
TypeError: Script.postprocess() missing 1 required positional argument: 'enabled'

Total progress: 100%|████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 6/6 [00:02<00:00,  2.05it/s]
Error running process: D:\stable-diffusion-webui\extensions\multidiffusion-upscaler-for-automatic1111\scripts\tilediffusion.py███████████████████| 6/6 [00:02<00:00,  2.70it/s]
Traceback (most recent call last):
  File "D:\stable-diffusion-webui\modules\scripts.py", line 417, in process
    script.process(p, *script_args)
TypeError: Script.process() missing 21 required positional arguments: 'enabled', 'method', 'overwrite_size', 'keep_input_size', 'image_width', 'image_height', 'tile_width', 'tile_height', 'overlap', 'tile_batch_size', 'upscaler_name', 'scale_factor', 'noise_inverse', 'noise_inverse_steps', 'noise_inverse_retouch', 'noise_inverse_renoise_strength', 'noise_inverse_renoise_kernel', 'control_tensor_cpu', 'enable_bbox_control', 'draw_background', and 'causal_layers'

Error running process: D:\stable-diffusion-webui\extensions\multidiffusion-upscaler-for-automatic1111\scripts\vae_optimize.py
Traceback (most recent call last):
  File "D:\stable-diffusion-webui\modules\scripts.py", line 417, in process
    script.process(p, *script_args)
TypeError: Script.process() missing 7 required positional arguments: 'enabled', 'encoder_tile_size', 'decoder_tile_size', 'vae_to_gpu', 'fast_decoder', 'fast_encoder', and 'color_fix'

Error running process_batch: D:\stable-diffusion-webui\extensions\sd-dynamic-thresholding\scripts\dynamic_thresholding.py
Traceback (most recent call last):
  File "D:\stable-diffusion-webui\modules\scripts.py", line 435, in process_batch
    script.process_batch(p, *script_args, **kwargs)
TypeError: Script.process_batch() missing 8 required positional arguments: 'enabled', 'mimic_scale', 'threshold_percentile', 'mimic_mode', 'mimic_scale_min', 'cfg_mode', 'cfg_scale_min', and 'powerscale_power'

 33%|██████████████████████████████████████████████▎                                                                                            | 4/12 [00:02<00:03,  2.07it/s]
```

However the video seems to be generated fine, so the errors are ignored or are not critical.

**Comment by cheezecrisp** [comment]
I met same issue when using 768x432 or 896x504 or some other resolution settings, only the first frame was generated and then it stopped

**Comment by volotat** [comment]
The FloweR model used to generate flow and occlusion prediction has input resolution restriction such that each side should be a multiple of 64. Basically same problem as with RAFT here https://github.com/volotat/SD-CN-Animation/issues/33#issuecomment-1537991750 with the similar solution of automatic resizing that would be implemented in the next update.

**Comment by volotat** [comment]
Please try to run it again on the new version of the extension.

**Comment by alexopus** [comment]
Same errors are still there after updating the extension. Here is another paste from a different machine:
```
Running on local URL:  http://127.0.0.1:7860

To create a public link, set `share=True` in `launch()`.
Startup time: 4.1s (import torch: 0.6s, import gradio: 0.5s, import ldm: 0.6s, other imports: 0.7s, setup codeformer: 0.1s, load scripts: 0.4s, load SD checkpoint: 0.9s, create ui: 0.3s).
Error running process: /home/user/stable-diffusion-webui/extensions/multidiffusion-upscaler-for-automatic1111/scripts/tilediffusion.py
Traceback (most recent call last):
  File "/home/user/stable-diffusion-webui/modules/scripts.py", line 417, in process
    script.process(p, *script_args)
TypeError: Script.process() missing 21 required positional arguments: 'enabled', 'method', 'overwrite_size', 'keep_input_size', 'image_width', 'image_height', 'tile_width', 'tile_height', 'overlap', 'tile_batch_size', 'upscaler_name', 'scale_factor', 'noise_inverse', 'noise_inverse_steps', 'noise_inverse_retouch', 'noise_inverse_renoise_strength', 'noise_inverse_renoise_kernel', 'control_tensor_cpu', 'enable_bbox_control', 'draw_background', and 'causal_layers'

Error running process: /home/user/stable-diffusion-webui/extensions/multidiffusion-upscaler-for-automatic1111/scripts/vae_optimize.py
Traceback (most recent call last):
  File "/home/user/stable-diffusion-webui/modules/scripts.py", line 417, in process
    script.process(p, *script_args)
TypeError: Script.process() missing 7 required positional arguments: 'enabled', 'encoder_tile_size', 'decoder_tile_size', 'vae_to_gpu', 'fast_decoder', 'fast_encoder', and 'color_fix'

Error running process_batch: /home/user/stable-diffusion-webui/extensions/sd-dynamic-thresholding/scripts/dynamic_thresholding.py
Traceback (most recent call last):
  File "/home/user/stable-diffusion-webui/modules/scripts.py", line 435, in process_batch
    script.process_batch(p, *script_args, **kwargs)
TypeError: Script.process_batch() missing 8 required positional arguments: 'enabled', 'mimic_scale', 'threshold_percentile', 'mimic_mode', 'mimic_scale_min', 'cfg_mode', 'cfg_scale_min', and 'powerscale_power'

100%|████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 15/15 [00:12<00:00,  1.22it/s]
Error running postprocess_batch: /home/user/stable-diffusion-webui/extensions/multidiffusion-upscaler-for-automatic1111/scripts/tilediffusion.py
Traceback (most recent call last):
  File "/home/user/stable-diffusion-webui/modules/scripts.py", line 453, in postprocess_batch
    script.postprocess_batch(p, *script_args, images=images, **kwargs)
TypeError: Script.postprocess_batch() missing 1 required positional argument: 'enabled'

Error running postprocess_batch: /home/user/stable-diffusion-webui/extensions/sd-dynamic-thresholding/scripts/dynamic_thresholding.py
Traceback (most recent call last):
  File "/home/user/stable-diffusion-webui/modules/scripts.py", line 453, in postprocess_batch
    script.postprocess_batch(p, *script_args, images=images, **kwargs)
TypeError: Script.postprocess_batch() missing 8 required positional arguments: 'enabled', 'mimic_scale', 'threshold_percentile', 'mimic_mode', 'mimic_scale_min', 'cfg_mode', 'cfg_scale_min', and 'powerscale_power'

Error running postprocess: /home/user/stable-diffusion-webui/extensions/multidiffusion-upscaler-for-automatic1111/scripts/tilediffusion.py
Traceback (most recent call last):
  File "/home/user/stable-diffusion-webui/modules/scripts.py", line 444, in postprocess
    script.postprocess(p, processed, *script_args)
TypeError: Script.postprocess() missing 1 required positional argument: 'enabled'

Error running postprocess: /home/user/stable-diffusion-webui/extensions/multidiffusion-upscaler-for-automatic1111/scripts/vae_optimize.py
Traceback (most recent call last):
  File "/home/user/stable-diffusion-webui/modules/scripts.py", line 444, in postprocess
    script.postprocess(p, processed, *script_args)
TypeError: Script.postprocess() missing 1 required positional argument: 'enabled'
```
Again, video is generated fine.
The errors go away if I disable the `multidiffusion-upscaler-for-automatic1111` and `sd-dynamic-thresholding` extensions, which seem to be failing here. So somehow there is a conflict, or those extensions act when they shouldn't.

**Comment by volotat** [comment]
The issue should be resolved now.

**Comment by alexopus** [comment]
Can confirm that these errors no longer appear in the latest version (d97ead6ab848443be94554f04acf39165704e998). Thanks!
