### ISSUE TITLE
Bug. "Traceback (most recent call last)"

### ISSUE THREAD

**Issue by Agnyy** [volotat/SD-CN-Animation#65]
GPU 3070
CPU - I7
OS - Windows 11

Unable to generate, throws an error.

Traceback (most recent call last):
  File "C:\Neural networks\Stable Diffusion\stable-diffusion-webui\venv\lib\site-packages\gradio\routes.py", line 337, in run_predict
    output = await app.get_blocks().process_api(
  File "C:\Neural networks\Stable Diffusion\stable-diffusion-webui\venv\lib\site-packages\gradio\blocks.py", line 1015, in process_api
    result = await self.call_function(
  File "C:\Neural networks\Stable Diffusion\stable-diffusion-webui\venv\lib\site-packages\gradio\blocks.py", line 843, in call_function
    raise ValueError("Need to enable queue to use generators.")
ValueError: Need to enable queue to use generators.
![image](https://github.com/volotat/SD-CN-Animation/assets/25137502/009d3c51-c1ff-489d-aa7f-46af0918035e)

**Comment by xieanbin** [comment]
in webui-user.bat,remove "no-gradio-queue ".moreover,don't use vpn.

**Comment by volotat** [comment]
@Agnyy Try to update webui to the latest version and restart it. Tell me if you will still have a problem after that.
