### ISSUE TITLE
Error loading script: base_ui.py

### ISSUE THREAD

**Issue by cbolich** [volotat/SD-CN-Animation#69]
Error loading script: base_ui.py
Traceback (most recent call last):
  File "/content/stable-diffusion-webui/modules/scripts.py", line 248, in load_scripts
    script_module = script_loading.load_module(scriptfile.path)
  File "/content/stable-diffusion-webui/modules/script_loading.py", line 11, in load_module
    module_spec.loader.exec_module(module)
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/content/stable-diffusion-webui/extensions/Reference-based-SD-CN-Animation/scripts/base_ui.py", line 30, in <module>
    from core import vid2vid, txt2vid, utils
ModuleNotFoundError: No module named 'core'

Got this error trying to run in a colab

**Comment by cbolich** [comment]
Just wanted to comment, reloaded the colab a few times and it worked.  It didn't work the first 3 times.

Also, keep getting kicked off of colab after about 10 minutes, runs fine on my local machine
