### ISSUE TITLE
RuntimeError('Attempting to deserialize object on a CUDA '

### ISSUE THREAD

**Issue by rezponze** [volotat/SD-CN-Animation#7]
1. I have installed both the repo and cloned the RAFT repo and downloaded the models. 
2. Modified script.py to update folders and connect to my 9090 SD port. 
3. I did a first test using and it renders the first frame of output.mp4 but then it stops and I get the following errors in the SD-CN-Animation console and Stable Diffusion UI console. 

I have a 3060 12Gb VRAM, using -xformers --medvram --port 9090 --api

This is the SD-CN-Animation script console output. (I've included the SD output below as well.)

Thanks in advance.

```
C:\Users\---\AI\SD-CN-Animation>python [script.py](https://script.py/)

OpenCV: FFMPEG: tag 0x5634504d/'MP4V' is not supported with codec id 12 and format 'mp4 / MP4 (MPEG-4 Part 14)'

OpenCV: FFMPEG: fallback to use tag 0x7634706d/'mp4v'

1%|█▌ | 1/99 [00:09<16:06, 9.87s/it]

Traceback (most recent call last):

File "C:\Users\\---\\AI\SD-CN-Animation\[script.py](https://script.py/)", line 234, in <module>

_, alpha_mask, warped_styled = RAFT_estimate_flow_diff(prev_frame, frame, prev_frame_styled)

File "C:\Users\\---\\AI\SD-CN-Animation\[script.py](https://script.py/)", line 100, in RAFT_estimate_flow_diff

RAFT_model.load_state_dict(torch.load(args.model))

File "C:\Users\\---\\AppData\Local\Programs\Python\Python310\lib\site-packages\torch\[serialization.py](https://serialization.py/)", line 789, in load

return _load(opened_zipfile, map_location, pickle_module, **pickle_load_args)

File "C:\Users\\---\\AppData\Local\Programs\Python\Python310\lib\site-packages\torch\[serialization.py](https://serialization.py/)", line 1131, in _load

result = unpickler.load()

File "C:\Users\\---\\AppData\Local\Programs\Python\Python310\lib\site-packages\torch\[serialization.py](https://serialization.py/)", line 1101, in persistent_load

load_tensor(dtype, nbytes, key, _maybe_decode_ascii(location))

File "C:\Users\\---\\AppData\Local\Programs\Python\Python310\lib\site-packages\torch\[serialization.py](https://serialization.py/)", line 1083, in load_tensor

wrap_storage=restore_location(storage, location),

File "C:\Users\\---\\AppData\Local\Programs\Python\Python310\lib\site-packages\torch\[serialization.py](https://serialization.py/)", line 215, in default_restore_location

result = fn(storage, location)

File "C:\Users\\---\\AppData\Local\Programs\Python\Python310\lib\site-packages\torch\[serialization.py](https://serialization.py/)", line 182, in _cuda_deserialize

device = validate_cuda_device(location)

File "C:\Users\\---\\AppData\Local\Programs\Python\Python310\lib\site-packages\torch\[serialization.py](https://serialization.py/)", line 166, in validate_cuda_device

raise RuntimeError('Attempting to deserialize object on a CUDA '

RuntimeError: Attempting to deserialize object on a CUDA device but torch.cuda.is_available() is False. If you are running on a CPU-only machine, please use torch.load with map_location=torch.device('cpu') to map your storages to the CPU.
```

Here is the SD output
```

Error running process: C:\Users\---\AI\AUTO\extensions\sd-webui-controlnet\scripts\[controlnet.py](https://controlnet.py/)

Traceback (most recent call last):

File "C:\Users\---\AI\AUTO\modules\[scripts.py](https://scripts.py/)", line 417, in process

script.process(p, *script_args)

File "C:\Users\---\AI\AUTO\extensions\sd-webui-controlnet\scripts\[controlnet.py](https://controlnet.py/)", line 629, in process

unit = self.parse_remote_call(p, unit, idx)

File "C:\Users\---\AI\AUTO\extensions\sd-webui-controlnet\scripts\[controlnet.py](https://controlnet.py/)", line 541, in parse_remote_call

unit.enabled = selector(p, "control_net_enabled", unit.enabled, idx, strict=True)

AttributeError: 'str' object has no attribute 'enabled'


100%|██████████████████████████████████████████████████████████████████████████████████| 10/10 [00:05<00:00, 1.83it/s]

Total progress: 50it [13:36, 4.54s/it]
```

**Comment by Cubey42** [comment]
you want to run the script in the venv while sd is running

**Comment by rezponze** [comment]
> you want to run the script in the venv while sd is running

Oh check! So, I should copy the SD-CN-Animation folder inside SD venv?
