### ISSUE TITLE
Possible new error from latest version

### ISSUE THREAD

**Issue by wordbrew** [volotat/SD-CN-Animation#70]
First off, loving the extension. Just installed v0.8 and now it is throwing the following error:

```
An exception occurred while trying to process the frame: list index out of range
Traceback (most recent call last):
  File "/content/gdrive/MyDrive/sd/stable-diffusion-webui/extensions/SD-CN-Animation/scripts/base_ui.py", line 114, in process
    yield from vid2vid.start_process(*args)
  File "/content/gdrive/MyDrive/sd/stable-diffusion-webui/extensions/SD-CN-Animation/scripts/core/vid2vid.py", line 114, in start_process
    utils.set_CNs_input_image(args_dict, Image.fromarray(curr_frame))
IndexError: list index out of range
```

When I start the process, it errors out almost immediately.

Hope this helps.

**Comment by volotat** [comment]
Do you have ControlNet extension installed? Vid2vid mode always supposed to be used with control net active.

**Comment by wordbrew** [comment]
Yup. Latest ControlNet installed and active. I restarted the session and it started processing, but am now getting a completely different error. I'm going to try completely restarting the server.

```
Traceback (most recent call last):
  File "/usr/local/lib/python3.10/dist-packages/gradio/routes.py", line 399, in run_predict
    output = await app.get_blocks().process_api(
  File "/usr/local/lib/python3.10/dist-packages/gradio/blocks.py", line 1302, in process_api
    data = self.postprocess_data(fn_index, result["prediction"], state)
  File "/usr/local/lib/python3.10/dist-packages/gradio/blocks.py", line 1236, in postprocess_data
    prediction_value = block.postprocess(prediction_value)
  File "/usr/local/lib/python3.10/dist-packages/gradio/components.py", line 2148, in postprocess
    processed_files = (self._format_video(y), None)
  File "/usr/local/lib/python3.10/dist-packages/gradio/components.py", line 2207, in _format_video
    video = self.make_temp_copy_if_needed(video)
  File "/usr/local/lib/python3.10/dist-packages/gradio/components.py", line 248, in make_temp_copy_if_needed
    temp_dir = self.hash_file(file_path)
  File "/usr/local/lib/python3.10/dist-packages/gradio/components.py", line 220, in hash_file
    with open(file_path, "rb") as f:
FileNotFoundError: [Errno 2] No such file or directory: ''
```

**Comment by shadowworksltd** [comment]
same errors after update (PC)

**Comment by volotat** [comment]
It is weird that there is nothing related to the extension in the traceback. I assume that there is some path location used in the script that is not correctly formatted for macos. Unfortunately I can't fix it without knowing where exactly the problem occurs in the script.

**Comment by wordbrew** [comment]
Took me a while to respond on this, but I'm actually using google colab, so that is linux operating system. So that means three of us have all run into the error, each on a different os (mac, windows, and linux). I'm using The Last Ben's Fast A1111

**Comment by Noofayroz** [comment]
> Took me a while to respond on this, but I'm actually using google colab, so that is linux operating system. So that means three of us have all run into the error, each on a different os (mac, windows, and linux). I'm using The Last Ben's Fast A1111

i have also the same issue on google Colab with The Last Ben's Fast A1111
