### ISSUE TITLE
ConnectionResetError: [WinError 10054] An existing connection was forcibly closed by the remote host

### ISSUE THREAD

**Issue by Optimusik** [volotat/SD-CN-Animation#83]
Today i got this error in the end of txt2vid job. Video was saved and work properly, but only this error in console disturbing me. Did 240 frames with 24 fps settings

Exception in callback _ProactorBasePipeTransport._call_connection_lost(None)███████████| 15/15 [00:02<00:00,  5.66it/s]
handle: <Handle _ProactorBasePipeTransport._call_connection_lost(None)>
Traceback (most recent call last):
  File "C:\Users\Asus\AppData\Local\Programs\Python\Python310\lib\asyncio\events.py", line 80, in _run
    self._context.run(self._callback, *self._args)
  File "C:\Users\Asus\AppData\Local\Programs\Python\Python310\lib\asyncio\proactor_events.py", line 162, in _call_connection_lost
    self._sock.shutdown(socket.SHUT_RDWR)
ConnectionResetError: [WinError 10054] An existing connection was forcibly closed by the remote host

**Comment by Dimart1** [comment]
Непонятно. Я думаю как сделать мультик по промпту просто.
--
Отправлено из Mail.ru для Android пятница, 12 мая 2023г., 15:20 +03:00 от Alexey Borsky  ***@***.*** :
