### ISSUE TITLE
Text2Video Generates numerous Extension related Errors, and does not listen to any parameter changes

### ISSUE THREAD

**Issue by mariaWitch** [volotat/SD-CN-Animation#86]
At the current moment, Text2Video causes Numerous errors all due to issues that aren't present on video2video. The specific issue is that extensions that modify image generation do not appear on text2video, and every extension that is expecting a value going into image generation does not receive it, and throws errors every time.

Example back trace
```python
Error running process: /home/maria/stable-diffusion-webui/extensions/multidiffusion-upscaler-for-automatic1111/scripts/tilediffusion.py
Traceback (most recent call last):
  File "/home/maria/stable-diffusion-webui/modules/scripts.py", line 417, in process
    script.process(p, *script_args)
TypeError: Script.process() missing 21 required positional arguments: 'enabled', 'method', 'overwrite_size', 'keep_input_size', 'image_width', 'image_height', 'tile_width', 'tile_height', 'overlap', 'tile_batch_size', 'upscaler_name', 'scale_factor', 'noise_inverse', 'noise_inverse_steps', 'noise_inverse_retouch', 'noise_inverse_renoise_strength', 'noise_inverse_renoise_kernel', 'control_tensor_cpu', 'enable_bbox_control', 'draw_background', and 'causal_layers'

Error running process: /home/maria/stable-diffusion-webui/extensions/multidiffusion-upscaler-for-automatic1111/scripts/vae_optimize.py
Traceback (most recent call last):
  File "/home/maria/stable-diffusion-webui/modules/scripts.py", line 417, in process
    script.process(p, *script_args)
TypeError: Script.process() missing 7 required positional arguments: 'enabled', 'encoder_tile_size', 'decoder_tile_size', 'vae_to_gpu', 'fast_decoder', 'fast_encoder', and 'color_fix'

Error running process: /home/maria/stable-diffusion-webui/extensions/sd-webui-llul/scripts/llul.py
Traceback (most recent call last):
  File "/home/maria/stable-diffusion-webui/modules/scripts.py", line 417, in process
    script.process(p, *script_args)
TypeError: Script.process() missing 13 required positional arguments: 'enabled', 'multiply', 'weight', 'understand', 'layers', 'apply_to', 'start_steps', 'max_steps', 'up', 'up_aa', 'down', 'down_aa', and 'intp'

Error running process: /home/maria/stable-diffusion-webui/extensions/sd-webui-regional-prompter/scripts/rp.py
Traceback (most recent call last):
  File "/home/maria/stable-diffusion-webui/modules/scripts.py", line 417, in process
    script.process(p, *script_args)
TypeError: Script.process() missing 14 required positional arguments: 'active', 'debug', 'mode', 'aratios', 'bratios', 'usebase', 'usecom', 'usencom', 'calcmode', 'nchangeand', 'lnter', 'lnur', 'threshold', and 'polymask'

Error running process: /home/maria/stable-diffusion-webui/extensions/sd_webui_SAG/scripts/SAG.py
Traceback (most recent call last):
  File "/home/maria/stable-diffusion-webui/modules/scripts.py", line 417, in process
    script.process(p, *script_args)
  File "/home/maria/stable-diffusion-webui/extensions/sd_webui_SAG/scripts/SAG.py", line 258, in process
    enabled, scale, mask_threshold = args
ValueError: not enough values to unpack (expected 3, got 0)

Error running process: /home/maria/stable-diffusion-webui/extensions/stable-diffusion-NPW/scripts/npw.py
Traceback (most recent call last):
  File "/home/maria/stable-diffusion-webui/modules/scripts.py", line 417, in process
    script.process(p, *script_args)
TypeError: Script.process() missing 1 required positional argument: 'weight'

Error running process: /home/maria/stable-diffusion-webui/extensions/stable-diffusion-webui-anti-burn/scripts/anti-burn.py
Traceback (most recent call last):
  File "/home/maria/stable-diffusion-webui/modules/scripts.py", line 417, in process
    script.process(p, *script_args)
TypeError: AntiBurnExtension.process() missing 8 required positional arguments: 'gr_enable', 'gr_debug', 'gr_count', 'gr_skip', 'gr_brute', 'gr_store', 'gr_stop', and 'gr_bug'

Error running process: /home/maria/stable-diffusion-webui/extensions/stable-diffusion-webui-composable-lora/scripts/composable_lora_script.py
Traceback (most recent call last):
  File "/home/maria/stable-diffusion-webui/modules/scripts.py", line 417, in process
    script.process(p, *script_args)
TypeError: ComposableLoraScript.process() missing 3 required positional arguments: 'enabled', 'opt_uc_text_model_encoder', and 'opt_uc_diffusion_model'

Error running process: /home/maria/stable-diffusion-webui/extensions/stable-diffusion-webui-two-shot-old/scripts/two_shot.py
Traceback (most recent call last):
  File "/home/maria/stable-diffusion-webui/modules/scripts.py", line 417, in process
    script.process(p, *script_args)
TypeError: Script.process() missing 5 required positional arguments: 'enabled', 'raw_divisions', 'raw_positions', 'raw_weights', and 'raw_end_at_step'

Error running before_process_batch: /home/maria/stable-diffusion-webui/extensions/sd-webui-regional-prompter/scripts/rp.py
Traceback (most recent call last):
  File "/home/maria/stable-diffusion-webui/modules/scripts.py", line 426, in before_process_batch
    script.before_process_batch(p, *script_args, **kwargs)
TypeError: Script.before_process_batch() missing 14 required positional arguments: 'active', 'debug', 'mode', 'aratios', 'bratios', 'usebase', 'usecom', 'usencom', 'calcmode', 'nchangeand', 'lnter', 'lnur', 'threshold', and 'polymask'

Error running process_batch: /home/maria/stable-diffusion-webui/extensions/sd-dynamic-thresholding/scripts/dynamic_thresholding.py
Traceback (most recent call last):
  File "/home/maria/stable-diffusion-webui/modules/scripts.py", line 435, in process_batch
    script.process_batch(p, *script_args, **kwargs)
TypeError: Script.process_batch() missing 8 required positional arguments: 'enabled', 'mimic_scale', 'threshold_percentile', 'mimic_mode', 'mimic_scale_min', 'cfg_mode', 'cfg_scale_min', and 'powerscale_power'

Error running process_batch: /home/maria/stable-diffusion-webui/extensions/sd-webui-additional-networks/scripts/additional_networks.py
Traceback (most recent call last):
  File "/home/maria/stable-diffusion-webui/modules/scripts.py", line 435, in process_batch
    script.process_batch(p, *script_args, **kwargs)
  File "/home/maria/stable-diffusion-webui/extensions/sd-webui-additional-networks/scripts/additional_networks.py", line 189, in process_batch
    if not args[0]:
IndexError: tuple index out of range

Error running process_batch: /home/maria/stable-diffusion-webui/extensions/sd-webui-regional-prompter/scripts/rp.py
Traceback (most recent call last):
  File "/home/maria/stable-diffusion-webui/modules/scripts.py", line 435, in process_batch
    script.process_batch(p, *script_args, **kwargs)
TypeError: Script.process_batch() missing 14 required positional arguments: 'active', 'debug', 'mode', 'aratios', 'bratios', 'usebase', 'usecom', 'usencom', 'calcmode', 'nchangeand', 'lnter', 'lnur', 'threshold', and 'polymask'

Error running process_batch: /home/maria/stable-diffusion-webui/extensions/stable-diffusion-webui-anti-burn/scripts/anti-burn.py
Traceback (most recent call last):
  File "/home/maria/stable-diffusion-webui/modules/scripts.py", line 435, in process_batch
    script.process_batch(p, *script_args, **kwargs)
TypeError: AntiBurnExtension.process_batch() missing 8 required positional arguments: 'gr_enable', 'gr_debug', 'gr_count', 'gr_skip', 'gr_brute', 'gr_store', 'gr_stop', and 'gr_bug'

100%|█████████████████████████████████████████████████████████████████████████| 15/15 [00:10<00:00,  1.43it/s]
Error running postprocess_batch: /home/maria/stable-diffusion-webui/extensions/multidiffusion-upscaler-for-automatic1111/scripts/tilediffusion.py
Traceback (most recent call last):
  File "/home/maria/stable-diffusion-webui/modules/scripts.py", line 453, in postprocess_batch
    script.postprocess_batch(p, *script_args, images=images, **kwargs)
TypeError: Script.postprocess_batch() missing 1 required positional argument: 'enabled'

Error running postprocess_batch: /home/maria/stable-diffusion-webui/extensions/sd-dynamic-thresholding/scripts/dynamic_thresholding.py
Traceback (most recent call last):
  File "/home/maria/stable-diffusion-webui/modules/scripts.py", line 453, in postprocess_batch
    script.postprocess_batch(p, *script_args, images=images, **kwargs)
TypeError: Script.postprocess_batch() missing 8 required positional arguments: 'enabled', 'mimic_scale', 'threshold_percentile', 'mimic_mode', 'mimic_scale_min', 'cfg_mode', 'cfg_scale_min', and 'powerscale_power'

Error running postprocess_batch: /home/maria/stable-diffusion-webui/extensions/stable-diffusion-webui-anti-burn/scripts/anti-burn.py
Traceback (most recent call last):
  File "/home/maria/stable-diffusion-webui/modules/scripts.py", line 453, in postprocess_batch
    script.postprocess_batch(p, *script_args, images=images, **kwargs)
TypeError: AntiBurnExtension.postprocess_batch() missing 8 required positional arguments: 'gr_enable', 'gr_debug', 'gr_count', 'gr_skip', 'gr_brute', 'gr_store', 'gr_stop', and 'gr_bug'

Error running postprocess_batch: /home/maria/stable-diffusion-webui/extensions/sd-webui-regional-prompter/scripts/rp.py
Traceback (most recent call last):
  File "/home/maria/stable-diffusion-webui/modules/scripts.py", line 462, in postprocess_image
    script.postprocess_image(p, pp, *script_args)
TypeError: Script.postprocess_image() missing 14 required positional arguments: 'active', 'debug', 'mode', 'aratios', 'bratios', 'usebase', 'usecom', 'usencom', 'calcmode', 'nchangeand', 'lnter', 'lnur', 'threshold', and 'polymask'

Error running postprocess: /home/maria/stable-diffusion-webui/extensions/multidiffusion-upscaler-for-automatic1111/scripts/tilediffusion.py
Traceback (most recent call last):
  File "/home/maria/stable-diffusion-webui/modules/scripts.py", line 444, in postprocess
    script.postprocess(p, processed, *script_args)
TypeError: Script.postprocess() missing 1 required positional argument: 'enabled'

Error running postprocess: /home/maria/stable-diffusion-webui/extensions/multidiffusion-upscaler-for-automatic1111/scripts/vae_optimize.py
Traceback (most recent call last):
  File "/home/maria/stable-diffusion-webui/modules/scripts.py", line 444, in postprocess
    script.postprocess(p, processed, *script_args)
TypeError: Script.postprocess() missing 1 required positional argument: 'enabled'

Error running postprocess: /home/maria/stable-diffusion-webui/extensions/sd-webui-llul/scripts/llul.py
Traceback (most recent call last):
  File "/home/maria/stable-diffusion-webui/modules/scripts.py", line 444, in postprocess
    script.postprocess(p, processed, *script_args)
TypeError: Script.postprocess() missing 13 required positional arguments: 'enabled', 'multiply', 'weight', 'understand', 'layers', 'apply_to', 'start_steps', 'max_steps', 'up', 'up_aa', 'down', 'down_aa', and 'intp'

Error running postprocess: /home/maria/stable-diffusion-webui/extensions/sd_webui_SAG/scripts/SAG.py
Traceback (most recent call last):
  File "/home/maria/stable-diffusion-webui/modules/scripts.py", line 444, in postprocess
    script.postprocess(p, processed, *script_args)
  File "/home/maria/stable-diffusion-webui/extensions/sd_webui_SAG/scripts/SAG.py", line 293, in postprocess
    enabled, scale, sag_mask_threshold = args
ValueError: not enough values to unpack (expected 3, got 0)
```

Additionally, all settings on the text2video panel do nothing in relation to image generation at the moment, and as such images are always generated at 15 steps, and what appears to always be euler a. In the example above, steps was set to 40, but images were only generated with 15 each time.

**Comment by rezponze** [comment]
I'm having the same error. Is this typo something I can edit myself or better wait for an update?

**Comment by mariaWitch** [comment]
The issue should be fully fixed with #87

**Comment by volotat** [comment]
@mariaWitch @rezponze Could you please check if the issue is still prevalent in the last commit?

**Comment by mariaWitch** [comment]
@volotat The newest commit fixed half of the problem. Extensions still error on the newest commit. See my comment on the PR.

**Comment by rezponze** [comment]
@volotat Same as @mariaWitch . I get this error:
Error running postprocess_batch: C:\Users\Joan\AI\AUTO_TORCH2\extensions\sd-webui-regional-prompter\scripts\rp.py6it/s]
Traceback (most recent call last):
  File "C:\Users\asdfg\AI\AUTO_TORCH2\modules\scripts.py", line 462, in postprocess_image
    script.postprocess_image(p, pp, *script_args)
TypeError: Script.postprocess_image() missing 14 required positional arguments: 'active', 'debug', 'mode', 'aratios', 'bratios', 'usebase', 'usecom', 'usencom', 'calcmode', 'nchangeand', 'lnter', 'lnur', 'threshold', and 'polymask'

Total progress: 100%|████████████████████████████████████████████████████████████████████| 6/6 [00:01<00:00,  4.13it/s]
Total progress: 100%|████████████████████████████████████████████████████████████████████| 6/6 [00:01<00:00,  4.56it/s]

**Comment by volotat** [comment]
The issue should be resolved now.
