### ISSUE TITLE
This makes controlnet plugin not work

### ISSUE THREAD

**Issue by kuyin** [volotat/SD-CN-Animation#95]
when this plugin turned on I can't use controlnet.

**Comment by kuyin** [comment]
Error running process: D:\Github\stable-diffusion-webui\extensions\sd-webui-controlnet\scripts\controlnet.py
Traceback (most recent call last):
  File "D:\Github\stable-diffusion-webui\modules\scripts.py", line 418, in process
    script.process(p, *script_args)
  File "D:\Github\stable-diffusion-webui\extensions\sd-webui-controlnet\scripts\controlnet.py", line 984, in process
    self.enabled_units = self.get_enabled_units(p)
  File "D:\Github\stable-diffusion-webui\extensions\sd-webui-controlnet\scripts\controlnet.py", line 943, in get_enabled_units
    unit = self.parse_remote_call(p, unit, idx)
  File "D:\Github\stable-diffusion-webui\extensions\sd-webui-controlnet\scripts\controlnet.py", line 795, in parse_remote_call
    unit.enabled = selector(p, "control_net_enabled", unit.enabled, idx, strict=True)
AttributeError: 'int' object has no attribute 'enabled'
