### ISSUE TITLE
Index out of range when generating a video (latest commit)

### ISSUE THREAD

**Issue by Pychnight** [volotat/SD-CN-Animation#96]
Error save prompt file
Traceback (most recent call last):
  File "D:\stable-diffusion-webui\extensions\sd-dynamic-prompts\sd_dynamic_prompts\callbacks.py", line 24, in on_save
    png_info = image_save_params.pnginfo["parameters"]
KeyError: 'parameters'
An exception occurred while trying to process the frame: list index out of range
Traceback (most recent call last):
  File "D:\stable-diffusion-webui\extensions\SD-CN-Animation\scripts\base_ui.py", line 141, in process
    yield from txt2vid.start_process(*args)
  File "D:\stable-diffusion-webui\extensions\SD-CN-Animation\scripts\core\txt2vid.py", line 156, in start_process
    processed_frame = np.array(processed_frames[0])
IndexError: list index out of range

seems like the newest commit has a conflict with some of the drop down add-ons, even if i disable the add-ons this issue shows up.

i had removed the add-on below but the above issue is still happening.
Traceback (most recent call last):
  File "D:\stable-diffusion-webui\extensions\sd-dynamic-prompts\sd_dynamic_prompts\callbacks.py", line 24, in on_save
    png_info = image_save_params.pnginfo["parameters"]
KeyError: 'parameters'
Error save prompt file
Traceback (most recent call last):
  File "D:\stable-diffusion-webui\extensions\sd-dynamic-prompts\sd_dynamic_prompts\callbacks.py", line 24, in on_save
    png_info = image_save_params.pnginfo["parameters"]

**Comment by alexmihaic** [comment]
Same here...

**Comment by Dimart1** [comment]
https://dimart.artstation.com
понедельник, 15 мая 2023г., 11:25 +03:00 от alexmihaic  ***@***.*** :

**Comment by darthzulder** [comment]
In ControlNet settings, you need to _uncheck_ the "Allow other script to control this extension".
That works for me.

**Comment by josephrocca** [comment]
> you need to uncheck the "Allow other script to control this extension"

Mine was already unchecked, but I tried checking it, and that fixed it

**Comment by DrNothing42** [comment]
Same! Wow, thanks!
Reddit was NO HELP with this. THIS was it! :):):)
